export interface CallRecord {
  id: string;
  contactId: string;
  type: 'incoming' | 'outgoing' | 'missed';
  timestamp: string; // ISO string
  duration?: string; // 예: "3분 45초"
  note?: string; // 통화 내용 요약/메모
}

export interface BusinessCard {
  id: string;
  name: string;
  company: string;
  department: string;
  title: string;
  phoneMobile: string; // 핸드폰
  phoneOffice: string; // 사무실
  phoneOffice2?: string; // 보조 유선전화/직통번호 등 (사무실2)
  phoneFax: string;    // 팩스
  email: string;
  address: string;
  address2?: string;   // 보조 주소 (공장/지사 등 주소가 2개인 경우)
  // [추가] 회사 주소(본사/공장 등)와는 별개로 관리한다. 개인정보라서, 명함 이미지(공유될
  // 수 있는 사진)에는 절대 그려 넣지 않고, 상세보기 화면의 텍스트 정보에만 표시한다.
  homeAddress?: string;
  website?: string;    // 홈페이지 주소
  lat?: number;
  // [추가] 예전엔 주소를 "강남/판교" 같은 동네 이름 몇 개로 대충 찍어서(가짜) 좌표를 항상
  // 채워뒀었다. 그래서 "좌표가 있는지 없는지"만으로는 진짜 지오코딩(카카오 API)으로
  // 정확히 계산된 건지, 예전 가짜값이 그대로 남아있는 건지 구분할 수 없었다. 이 값이
  // true여야 "실제 API로 확인된 정확한 좌표"라는 뜻이다.
  isRealGeocoded?: boolean;
  lng?: number;
  groupId?: string; // [구버전 호환용] 예전에는 그룹 하나만 저장했다. 기존 데이터 호환을 위해 남겨둠.
  // [추가] 명함 하나가 여러 그룹에 동시에 속할 수 있도록 배열로 변경. 새로 저장되는 데이터는
  // 이 필드를 쓴다. groupId(단수)만 있는 예전 데이터는 화면에서 자동으로 [groupId] 취급한다
  // (src/groupUtils.ts의 getContactGroupIds 참고).
  groupIds?: string[];
  frontImage?: string; // base64 data url or sample image
  backImage?: string;
  memo?: string;
  companyInfo?: string; // 회사 간략 요약 정보
  // [수정] 팀/부서별 공유 범위를 위해 이 명함을 누가 등록했는지 기록. isPrivate가 true면
  // 등록한 본인 외에는(같은 회사 소속이라도) 조회 목록에서 보이지 않는다.
  addedByUserId?: string;
  addedByUserName?: string;
  isPrivate?: boolean; // true면 "나만 보기(비공개)" - 등록한 본인에게만 보임
  // [추가] 가져오기(import) 시 사진이 없어서 이름/회사 정보로 자동으로 그려준 명함 이미지인지 표시.
  // true면, 나중에 이름 등을 수정할 때 이 정보를 반영해서 이미지를 자동으로 다시 그려준다.
  // 실제 사진을 촬영/업로드하면 이 값은 false가 되어 더 이상 자동으로 덮어쓰지 않는다.
  isAutoGeneratedImage?: boolean;
  createdAt: string;
  callHistory: CallRecord[];
}

export interface ContactGroup {
  id: string;
  name: string;
  color: string;
  count?: number;
  // [추가] 그룹 자체를 "나만 보기(비공개)"로 설정할 수 있게 한다. 예전엔 명함 하나하나에만
  // 공개/비공개를 정할 수 있어서, 그룹에 새로 들어오는 명함마다 매번 손으로 다시 비공개
  // 처리해야 했고, 그룹 이름 자체(필터 칩, 그룹 관리 목록)는 항상 회사 전체에 보였다.
  // 그룹에 공개 설정을 두면 그룹 자체도 숨길 수 있고, 그 안에 속한 명함도 함께 숨겨진다
  // (명함 각각의 개별 isPrivate 설정과 별개로, 그룹 비공개가 우선 적용된다).
  createdByUserId?: string;
  createdByUserName?: string;
  isPrivate?: boolean; // true면 "나만 보기(비공개)" - 만든 본인에게만 보임
}

export interface ScanCardResult {
  name: string;
  company: string;
  department: string;
  title: string;
  phoneMobile: string;
  phoneOffice: string;
  phoneOffice2?: string;
  phoneFax: string;
  email: string;
  address: string;
  address2?: string;
  memo?: string;
  companyInfo?: string; // 회사 요약 정보
}

export interface ProjectFollowUpAttachment {
  id: string;
  name: string;      // 파일명
  dataUrl: string;   // base64 데이터 (제안서, 견적서 등 첨부파일)
  size?: number;      // 바이트 단위 파일 크기 (표시용)
}

// [추가] "경영지원"/"회계관리" 탭 - 관리자만 볼 수 있는 회사 서류·장부 보관함.
// 서류 종류(근로계약서, 급여명세서 등)마다 필요한 항목이 조금씩 다르지만, 실제로는
// "제목 + 날짜 + 관련자 + 금액(있으면) + 메모 + 첨부파일" 정도로 충분히 다 담을 수 있어서,
// 12개 종류를 전부 따로 만들지 않고 하나의 공용 구조에 category만 다르게 저장한다.
export type AdminDocSection = 'management' | 'accounting';
export type AdminDocCategory =
  // 경영지원
  | 'labor_contract'      // 근로계약서
  | 'salary_agreement'    // 연봉협약서
  | 'employment_cert'     // 재직증명서
  | 'office_supplies'     // 사무실 비품 관리
  | 'sales_contract'      // 영업 계약
  | 'corp_card'           // 법인카드 관리
  // 회계관리
  | 'payslip'             // 급여명세서
  | 'severance'           // 퇴직금 정산
  | 'monthly_cashflow'    // 월별 자금 현황
  | 'bank_withdrawal'     // 통장 출금 내역
  | 'bank_deposit'        // 통장 입금 내역
  | 'loan_repayment'      // 대출 현황
  | 'card_usage';         // 법인카드 사용내역

export interface AdminDocLineItem {
  id: string;
  label: string;
  amount: number;
  // [추가] 4대보험 공제액 자동계산 기준(과세 대상 급여)에 포함할지 여부. 식대·차량유지비처럼
  // 비과세 항목(일정 한도까지 세금·보험료 계산에서 제외되는 항목)은 false로 둔다.
  // 지급 내역에서만 의미가 있고, 공제 내역에는 안 쓰인다.
  taxable?: boolean;
}

export interface AdminDoc {
  id: string;
  section: AdminDocSection;
  category: AdminDocCategory;
  title: string;          // 제목 (예: "2026년 홍길동 근로계약서")
  date: string;            // 기준 날짜 (YYYY-MM-DD) - 계약일, 지급일, 거래일 등
  personName?: string;     // 관련자/거래처명 (직원명, 카드 소지자, 거래처 등)
  amount?: string;         // 금액 (있는 경우) - 문자열로 저장, 표시할 때 콤마 포맷팅
  memo?: string;
  attachments?: ProjectFollowUpAttachment[]; // 계약서/명세서 등 첨부파일(PDF, 이미지 등)
  createdByUserId?: string;
  createdByUserName?: string;
  createdAt: string;
  // [추가] 급여명세서(category: 'payslip') 전용 구조화 필드. 실제 회사 급여명세서 양식
  // (사원코드/입사일/부서/직위/호봉 + 지급내역·공제내역 각각 여러 줄)을 그대로 담기 위해
  // 다른 서류들과 별도로 필드를 둔다. 급여명세서가 아닌 다른 서류에서는 안 쓰인다.
  payslip?: {
    companyName?: string;
    payMonth?: string;      // 예: "2026-07" (몇 월분 급여인지)
    paymentDate?: string;   // 지급일 (YYYY-MM-DD)
    employeeCode?: string;  // 사원코드
    hireDate?: string;      // 입사일
    department?: string;    // 부서
    position?: string;      // 직위
    salaryGrade?: string;   // 호봉
    // [추가] 4대보험 등 공제율(%). 매년 바뀌는 값이라 화면에서 직접 조정할 수 있게 하고,
    // 이 급여명세서를 저장할 때 그 시점에 쓴 값을 그대로 남겨서, 나중에 요율이 바뀌어도
    // 예전에 발급한 명세서의 계산 근거가 그대로 유지되게 한다(소급 재계산되지 않음).
    rates?: {
      pensionRate: number;     // 국민연금 (기본 4.75%)
      healthRate: number;      // 건강보험 (기본 3.595%)
      ltcRate: number;         // 장기요양보험료 - 건강보험료에 곱하는 비율 (기본 13.14%)
      employmentRate: number;  // 고용보험 (기본 0.9%)
      localTaxRate: number;    // 지방소득세 - 소득세에 곱하는 비율 (기본 10%)
    };
    payItems: AdminDocLineItem[];        // 지급 내역 (기본급, 연장수당, 식대 등)
    deductionItems: AdminDocLineItem[];  // 공제 내역 (국민연금, 건강보험, 소득세 등)
  };
  // [추가] 월별 자금 현황(category: 'monthly_cashflow') 전용 구조화 필드. 통장(계좌)별
  // 이월금/입금/출금을 각각 입력하면 통장잔액은 자동 계산되고, 합계도 자동으로 더해진다.
  cashflow?: {
    periodStart?: string; // 집계 시작일 (YYYY-MM-DD)
    periodEnd?: string;   // 집계 종료일 (YYYY-MM-DD)
    accounts: {
      id: string;
      // [수정] 예전엔 "구분" 한 칸에 은행/계좌/용도를 다 합쳐서 문자열로 적었는데, 이러면
      // 통장 입금/출금 내역과 "같은 통장"인지 프로그램이 알아볼 방법이 없었다. 은행명·
      // 계좌번호를 별도 필드로 분리해서, 같은 은행+계좌를 쓰는 입금/출금 내역과 자동으로
      // 매칭해 금액을 맞출 수 있게 한다.
      bankName?: string;      // 은행 (예: "하나은행")
      accountNumber?: string; // 계좌번호 (예: "110-123-456789")
      subCategory?: string;   // 구분/용도 (예: "급여/외화송금/카드대금")
      broughtForward: number; // 이월금(원) - 전월에서 넘어온 잔액
      deposit: number;        // 입금(원) - 직접 입력하거나 "자동 불러오기"로 입금내역에서 합산
      withdrawal: number;     // 출금(원) - 직접 입력하거나 "자동 불러오기"로 출금내역에서 합산
      note?: string;           // 비고
    }[];
  };
  // [추가] 통장 출금/입금 내역(category: 'bank_withdrawal' | 'bank_deposit') 공용 구조화
  // 필드. 두 카테고리가 "통장(계좌)별로 날짜/프로젝트/금액/거래내용/비고가 여러 줄, 계좌마다
  // 소계, 맨 아래 총합계" 구조로 완전히 똑같아서 하나의 타입을 같이 쓴다.
  bankLedger?: {
    accounts: {
      id: string;
      // [수정] 예전엔 표시 이름(accountName) + 은행/계좌번호가 따로 있어서 입력이 두 번
      // 겹쳤다. 월별 자금 현황과 완전히 똑같이 은행/계좌번호/구분 3칸으로 통일한다 —
      // 이러면 화면 구조도 똑같아지고, 자금 현황과 매칭시킬 때도 헷갈릴 일이 없다.
      bankName?: string;      // 은행 (예: "하나은행")
      accountNumber?: string; // 계좌번호
      subCategory?: string;   // 구분/용도 (예: "급여/외화송금/카드대금")
      entries: {
        id: string;
        date: string;         // 일자 (YYYY-MM-DD)
        project: string;      // 프로젝트
        amount: number;       // 금액(원)
        description: string;  // 거래내용
        note?: string;         // 비고
      }[];
    }[];
  };
  // [추가] 대출이자 및 원금 상환 내역(category: 'loan_repayment') 전용 구조화 필드.
  // 대출 건별로 대출금액/이자율/만기/대출잔액/이번 출금(원금+이자)/출금통장을 입력하고,
  // 상환이 끝난 대출은 isRepaid로 표시해서 "상환완료" 구역에 따로 모아 보여준다.
  // [수정] 실제로 회사에서 쓰시는 "대출 현황" 양식에 맞춰 항목을 더 세분화했다: 대출명과
  // 대출계좌를 분리, 이자율을 최초/현재로 분리, 대출일을 추가, 만기일과 납기일을 분리,
  // 출금통장도 은행/계좌로 분리 - 자금현황·통장내역과 동일하게 은행/계좌를 나누는 방식을
  // 따른다.
  loanRepayment?: {
    loans: {
      id: string;
      loanName: string;        // 대출 명 (예: "우리은행_중진직대출")
      loanAccount?: string;    // 대출 계좌
      initialAmount: number;   // 대출 금액(원) - 최초 대출 원금
      initialRate: number;     // 최초 이자율(%)
      currentRate: number;     // 현재 이자율(%)
      loanDate?: string;       // 대출일 (YYYY-MM-DD)
      maturityDate?: string;   // 만기일 (YYYY-MM-DD)
      paymentDay?: string;     // 납기일 (예: "29일")
      balance: number;         // 대출잔액(원) - 현재 남은 원금
      principalPaid: number;   // 출금 금액 - 원금
      interestPaid: number;    // 출금 금액 - 이자 (원금+이자 = 계, 자동 계산)
      withdrawBank?: string;   // 출금 은행
      withdrawAccount?: string; // 출금 계좌
      isRepaid: boolean;       // 상환완료 여부 - 켜면 "상환완료" 구역으로 분류
      repaidDate?: string;     // 상환일 (상환완료인 경우)
      repaidFee?: string;      // 상환수수료 등 메모 (선택)
      note?: string;
    }[];
  };
  // [추가] 법인카드 사용내역(category: 'card_usage') 전용 구조화 필드. 카드(소지자)별로
  // 묶어서 여러 사용 내역(금액/일자/프로젝트명/사용자/비고)을 입력하고, 카드마다 소계,
  // 맨 아래 총계가 자동으로 계산된다. 통장 출금/입금 내역과 구조가 같다.
  cardUsage?: {
    cards: {
      id: string;
      cardName: string;   // 카드명 (예: "국민카드", "하나카드")
      cardNumber?: string; // 카드번호
      holder: string;      // 소지자
      entries: {
        id: string;
        amount: number;    // 사용 금액(원)
        date: string;       // 사용일자 (YYYY-MM-DD)
        project?: string;   // 프로젝트명
        user?: string;      // 사용자 (소지자와 다를 수 있음, 예: 법인카드 대여)
        note?: string;       // 비고
        // [추가] 통합 차량 관리(비용관리/정비일지)·프로젝트·업무일지(일일/주간)에서 이미
        // "법인카드" 결제로 기록된 지출을 "자동 불러오기"로 가져온 경우, 그 원본을
        // 추적하기 위한 값. 사람이 직접 입력한 항목은 이 값이 없다. sourceKey로 같은
        // 원본을 중복으로 다시 가져오지 않도록 막는다.
        sourceKey?: string;
        sourceLabel?: string; // 화면에 보여줄 원본 이름 (예: "차량 비용관리")
      }[];
    }[];
  };
}

export interface MeetingExpenseItem {
  id: string;
  category: 'meal' | 'drinks' | 'purchase' | 'service_fee' | 'custom'; // 식대 / 음료(커피) / 물품 구입 / 식사 서비스 비용 / 직접 입력
  categoryCustom?: string; // 직접 입력 시 카테고리명
  amount: number;
  payMethod: 'company_card' | 'personal_card' | 'cash'; // 법인(회사)카드 / 개인카드 / 현금
  memo?: string; // 지출 상세 사유/메모
  receiptImage?: string; // 스캔하거나 첨부한 영수증 사진 (base64)
}

export interface ProjectFollowUp {
  id: string;
  projectId: string;
  content: string;
  date: string;
  status: 'planned' | 'in_progress' | 'done';
  meetingDegree?: number;   // 1차 미팅, 2차 미팅 등 차수 (제한 없음, 비워두면 '업무 기록'으로 표시)
  meetingType?: 'meeting' | 'followup'; // 같은 차수 안에서 "미팅"인지 "팔로우업"인지 구분
  attendee?: string;       // 미팅 참여 담당자 (미팅자, 거래처/고객 측)
  internalStaffName?: string; // 우리 회사 담당 직원 (같은 회사로 가입한 계정 중 선택)
  hasVoice?: boolean;      // 음성 메모 녹음 여부
  voiceUrl?: string;       // 음성 재생용 (시뮬레이션 혹은 실제 녹음 데이터)
  voiceDuration?: string;  // 음성 녹음 분초 (예: "0:15")
  attachments?: ProjectFollowUpAttachment[]; // 제안서/견적서/발송자료 등 첨부파일
  expenses?: MeetingExpenseItem[]; // 미팅/팔로우업 관련 지출 비용 (영수증 스캔 포함)
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  salesRep?: string;           // 영업자(담당자) - 이 프로젝트를 등록/담당하는 내부 영업 담당자 (기본값: 등록자 본인)
  developer?: string;          // 시행사(발주처)
  contractor?: string;         // 시공사
  architect?: string;          // 건축설계사
  interiorDesigner?: string;   // 인테리어설계사
  electricalDesigner?: string; // 전기설계사
  mechanicalDesigner?: string; // 기계설계사
  supervisor?: string;         // 감리사
  operator?: string;           // 운영사
  status: 'opportunity' | 'progress' | 'completed' | 'failed';
  priority: 'high' | 'medium' | 'low';
  dueDate: string;
  contactIds: string[]; // 연관된 거래처 명함 ID 목록
  budget?: string;
  followUps: ProjectFollowUp[];
  createdAt: string;
}

export interface MyProfile {
  name: string;
  company: string;
  department: string;
  title: string;
  phoneMobile: string;
  phoneOffice: string;
  phoneFax: string;
  email: string;
  address: string;
  snsUrl?: string;
  website?: string;
  memo?: string;
  // [수정] 내 명함 앞/뒷면 스캔 사진을 프로필과 함께 저장/조회할 수 있도록 추가
  // (기존에는 이 필드가 없어서 촬영한 사진이 AI 인식에만 잠깐 쓰이고 저장되지 않았음)
  frontImage?: string; // base64 data url
  backImage?: string;  // base64 data url
  // [수정] 공유용 랜딩 페이지(/s/:slug)에 쓰이는 공개 식별자. 최초 조회 시 서버가 자동 생성해서 저장한다.
  shareSlug?: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  type: 'individual' | 'company';
  companyName?: string;
  businessNumber?: string;
  // [수정] 운영 현황에서 가입자 연락처를 확인할 수 있도록 (선택 입력)
  phone?: string;
  // [수정] 코드 곳곳에서 이미 사용 중이었는데 타입 선언이 빠져있던 필드들
  // (직책 / 회사 내 역할). 회사(type: 'company') 회원에게만 의미가 있다.
  position?: string;
  role?: 'admin' | 'member';
  // [추가] 회사 회원가입 승인 상태. 같은 사업자번호로 가입하는 두 번째 이후 사용자는
  // 'pending'으로 시작해서, 그 회사 관리자가 승인해야 'approved'로 바뀌고 그제서야
  // 회사 데이터(명함/프로젝트 등)에 접근할 수 있다. 최초 가입자(관리자)는 바로 'approved'.
  // 값이 없는(undefined) 기존 계정들은 이 기능이 생기기 전에 가입한 것이므로 승인된 것으로 간주한다.
  approvalStatus?: 'approved' | 'pending';
  // [추가] 이메일 인증 여부. 가입 시 false로 시작하고, 메일로 받은 링크를 클릭해야
  // true가 된다. 값이 없는(undefined) 기존 계정은 이 기능이 생기기 전에 가입한
  // 것이므로 인증된 것으로 간주한다(true 취급).
  emailVerified?: boolean;
  // [추가] 토스페이먼츠 구독 결제 상태. 회사(company) 관리자 계정에만 의미가 있다 —
  // 그 회사 전체의 구독 여부를 관리자 한 명의 결제 정보로 관리한다.
  // - plan: 'free'(무료, 기본 기능만) | 'pro'(구독 결제 완료, 전체 기능)
  // - subscriptionStatus: 결제 진행 상태. 'active'가 아니면 pro 기능이 잠긴다.
  plan?: 'free' | 'pro';
  subscriptionStatus?: 'none' | 'active' | 'past_due' | 'canceled';
  nextBillingAt?: string; // ISO 날짜문자열 — 다음 자동결제 예정일
  // [추가] 가입 일시. "가입 회원 & 협업 디렉토리"/운영현황에서 회사를 최근 가입순으로
  // 정렬하는 데 사용한다.
  createdAt?: string;
}

export interface RegisteredUser extends User {
  password?: string;
  // [수정] 언제 가입했는지 확인할 수 있도록 가입 일시 기록. 이 필드가 생기기 전에 이미
  // 가입되어 있던 계정은 값이 없을 수 있다(운영 현황 화면에서 "정보 없음"으로 표시).
  createdAt?: string;
  // [추가] 이메일 인증 토큰/만료시각 (서버 내부용, 클라이언트로는 절대 내려주지 않음)
  emailVerificationToken?: string;
  emailVerificationTokenExpiresAt?: number;
  // [추가] 토스페이먼츠 연동용 서버 전용 필드 (클라이언트로는 절대 내려주지 않음)
  // - tossCustomerKey: 토스에 등록하는 구매자 식별키 (추측 불가능한 무작위 값이어야 함)
  // - tossBillingKey: 카드 등록 완료 후 발급되는 빌링키. 이걸로 매달 자동결제를 청구한다.
  //   토스 정책상 한 번 발급되면 다시 조회할 수 없으므로, 발급 즉시 안전하게 저장해야 한다.
  tossCustomerKey?: string;
  tossBillingKey?: string;
  // [추가] 애플 캘린더(아이폰/아이패드/맥) 구독 연동용 토큰. 캘린더 앱은 로그인 세션 없이
  // 그냥 URL 하나로 주기적으로 GET 요청만 보내기 때문에, x-user-id 헤더 같은 일반
  // 인증 방식을 못 쓴다. 대신 추측 불가능한 무작위 토큰을 URL에 담아서 그 사람(회사
  // 스코프)을 식별한다. 최초로 "Apple 캘린더 연동" 기능을 켤 때 한 번 생성되고, 이후
  // 계속 재사용된다.
  calendarFeedToken?: string;
}

// === 통합 차량 관리 (Vehicle Management) ===

export interface Vehicle {
  id: string;
  modelName: string;     // 차량명 (예: 벤츠 E300 4Matic)
  plateNumber: string;   // 차량 번호 (예: 12가 3456)
  owner: string;         // 담당자 / 운전자
  purchaseDate: string;  // 구입/대여 일자
  initialMileage: number; // 최초 주행거리 (km)
  currentMileage: number; // 현재 주행거리 (km)
  fuelType: 'gasoline' | 'diesel' | 'hybrid' | 'electric' | 'lpg'; // 유종
  status: 'active' | 'maintenance' | 'retired'; // 운행가능, 정비중, 운행중단
  createdAt: string;
  // --- 추가된 필드들 ---
  modelYear?: string;     // 년식 (예: 2024년식)
  color?: string;         // 색상
  rentalType?: 'own' | 'long_rent' | 'lease' | 'short_rent' | 'short_lease'; // 임차구분
  rentalFee?: number;     // 임차료 (월, 원)
  insuranceCompany?: string; // 보험사
  insuranceStartDate?: string; // 보험 가입일자
  insuranceEndDate?: string;   // 보험 만기일자
  insuranceAgent?: string;     // 보험 담당자
  insuranceContact?: string;   // 보험 연락처
  beaconId?: string;           // 비콘 ID
  registrationDocumentUrl?: string; // 자동차 등록증 이미지/파일 URL (base64)
}

export interface DrivingLog {
  id: string;
  vehicleId: string;
  driverName: string;    // 운전자명
  date: string;          // 운행 일자
  purpose: string;       // 운행 목적 (업무용, 출퇴근, 출장 등)
  startMileage: number;  // 출발 시 주행거리 (km)
  endMileage: number;    // 도착 시 주행거리 (km)
  distance: number;      // 주행거리 (km)
  startPlace?: string;   // 출발지
  endPlace?: string;     // 목적지
  department?: string;   // 부서
  projectName?: string;  // 프로젝트명
  startAddress?: string; // 출발지 주소
  endAddress?: string;   // 목적지 주소
  memo?: string;         // 메모
  createdAt: string;
  contactId?: string;    // 연관 거래처 담당자 ID
}

export interface VehicleExpense {
  id: string;
  vehicleId: string;
  date: string;          // 지출 일자
  category: 'fuel' | 'toll' | 'parking' | 'maintenance' | 'tax_insurance' | 'other' | 'agency_drive' | 'beverage' | 'meal' | 'supplies' | 'custom'; // 주유비, 통행료, 주차비, 정비비, 세금/보험, 기타, 대리운전비, 음료, 식대, 물품 구입, 직접 입력
  categoryCustom?: string; // 직접 입력 카테고리명
  amount: number;        // 지출 금액 (원)
  memo?: string;         // 메모
  payMethod?: 'company_card' | 'personal_card' | 'cash'; // 결제 수단
  merchantName?: string;  // 상호명
  fuelVolume?: number;    // 주유량 (L)
  projectName?: string;   // 프로젝트명
  createdAt: string;
  contactId?: string;    // 연관 거래처 담당자 ID
  receiptImage?: string; // 영수증 이미지 (base64)
  // [추가] 운행기록 작성 중 스캔한 영수증인 경우, 어느 운행기록에서 나온 지출인지 연결.
  // 이 값이 있으면 운행기록 수정 화면에서 "이미 등록된 영수증 목록"으로 다시 불러와 보여줄 수 있다.
  drivingLogId?: string;
}

export interface VehicleMaintenance {
  id: string;
  vehicleId: string;
  date: string;          // 정비 예정/완료 일자
  title: string;         // 정비 내용 (예: 엔진오일 교환)
  cost: number;          // 정비 비용 (원)
  mileage: number;       // 정비 시점 주행거리 (km)
  shopName?: string;     // 정비소명
  shopContact?: string;  // 정비소 연락처
  status: 'scheduled' | 'completed'; // 예정됨, 정비완료
  memo?: string;         // 메모
  payMethod?: 'company_card' | 'personal_card' | 'cash'; // 결제 수단
  receiptImage?: string; // 정비 영수증/청구서 이미지 (base64)
  createdAt: string;
}

export interface MaintenanceInterval {
  id: string;
  vehicleId: string;
  itemType: string;         // 점검 항목 (엔진오일 교환 등)
  intervalKm?: number;      // km 주기
  intervalDays?: number;    // 일 주기
  lastServiceMileage?: number; // 마지막 점검 주행 거리 (km)
  lastServiceDate?: string; // 마지막 점검일
  alertKmBefore?: number;   // km 전 알림
  alertDaysBefore?: number; // 일 전 알림
  createdAt: string;
}

export interface WorkLogExpense {
  id: string;
  category: 'breakfast' | 'lunch' | 'dinner' | 'drinks' | 'fuel' | 'parking' | 'proxy' | 'purchase' | 'custom';
  categoryCustom?: string; // 직접 입력시 카테고리명
  amount: number;        // 지출 금액 (원)
  payMethod: 'company_card' | 'personal_card' | 'cash_personal' | 'cash_company'; // 결제 수단
  memo?: string;         // 메모
  vehicleId?: string;    // 연동된 차량 ID (선택)
  linkedVehicleExpenseId?: string; // 연동된 차량비용 ID (상호 연동용)
  receiptImage?: string; // 영수증 이미지 (base64)
}

export interface DailyWorkLog {
  id: string;
  date: string;          // 일일 일자 (YYYY-MM-DD)
  title: string;         // 제목
  author?: string;       // 작성자
  department?: string;   // 부서
  tasksToday: string;    // 금일 실시 사항 (taskEntriesToday를 합쳐서 만든 텍스트, 인쇄/엑셀/AI정제용)
  taskEntriesToday?: WorkLogDayEntry[]; // 금일 실시 사항 항목 목록 (하루에 여러 건, 각각 시작~종료 시간 지정 가능)
  tasksTomorrow: string; // 명일 예정 사항
  issues?: string;       // 특이 사항/미결 사항
  contactIds?: string[];  // 연관 거래처/인맥 ID 목록 (명함 ID)
  projectIds?: string[];  // 연관 프로젝트 ID 목록
  expenses?: WorkLogExpense[]; // 비용 추가 항목 리스트
  createdAt: string;
}

export interface WorkLogDayEntry {
  id: string;
  startTime?: string;   // 시작 시간 (예: "09:00")
  endTime?: string;     // 종료 시간 (예: "10:30")
  content: string;      // 해당 시간대 업무 내용
}

// === 전자결재 (Electronic Approval) ===

export type ApprovalStatus = 'draft' | 'pending' | 'approved' | 'rejected';

// 결재선 한 단계 (예: 기안자 / 경영지원실장 / 기술이사 / 대표이사)
export interface ApprovalStep {
  role: string;   // 직책/직위 라벨
  name?: string;   // 결재자 이름
  date?: string;   // 결재(승인) 일자 YYYY-MM-DD, 비어있으면 미결
}

export type LeaveCategory =
  | 'monthly'   // 월차
  | 'annual'    // 연차
  | 'official'  // 공가
  | 'sick'      // 병가
  | 'special'   // 특별휴가 (세부 종류는 specialType 필드로 구분: 출산/하기/경조/재해/직접입력)
  | 'health'    // 보건
  | 'other';    // 기타

export type LeaveSpecialType = 'birth' | 'summer' | 'family' | 'disaster' | 'custom';

// 연차 사용 단위: 년차(하루 종일, 1일) / 반차(4시간, 0.5일) / 반반차(2시간, 0.25일)
export type LeaveAnnualType = 'full' | 'half' | 'quarter';

// 휴가 신청서
export interface LeaveRequest {
  id: string;
  draftNumber: string;         // 기안번호 (예: 20260708-01)
  department: string;           // 소속
  author: string;                // 휴가자
  leaveCategory: LeaveCategory;  // 휴가 구분
  leaveCategoryCustom?: string;  // 기타 선택시 직접 입력
  specialType?: LeaveSpecialType;   // 특별휴가 선택시 세부 종류
  specialTypeCustom?: string;       // 특별휴가 세부 종류가 직접입력일 때의 텍스트
  annualType?: LeaveAnnualType;     // 연차 선택시 사용 단위 (년차/반차/반반차)
  totalAnnualDays?: number;         // 연차 선택시, 그 해 전체 부여된 연차 일수 (누적 표기 계산용)
  reason: string;                // 사유
  startDate: string;             // 시작일 YYYY-MM-DD
  endDate: string;               // 종료일 YYYY-MM-DD
  startTime?: string;            // 시작 시간 (반차 등)
  endTime?: string;              // 종료 시간
  days: number;                   // 산정된 휴가 일수
  annualLeaveNote?: string;      // 연차 사용/잔여 표기 (예: "5일/20일")
  homeContact?: string;          // 자택 연락처
  mobileContact?: string;        // 휴대폰
  actingPerson?: string;         // 직무 대행자
  submittedDate: string;         // 신청일 (문서 하단 날짜)
  approvalLine: ApprovalStep[];  // 결재선
  status: ApprovalStatus;
  approverMemo?: string;
  createdAt: string;
}

export interface AdvancePaymentItem {
  id: string;
  date: string;          // 날짜
  project?: string;       // 프로젝트명
  description: string;    // 내용
  amount: number;          // 금액(원)
  account?: string;        // 계정과목
  companyName?: string;    // 상호
  remark?: string;         // 비고
  // [수정] 차량비용/정비/업무일지에서 "가져오기" 할 때 원본에 첨부된 영수증 사진도 같이 가져오기 위한 필드
  receiptImage?: string;
}

// 가지급금 정산서
export interface AdvancePaymentSettlement {
  id: string;
  companyName: string;     // 회사명
  periodStart: string;      // 기간 시작
  periodEnd: string;        // 기간 종료
  department: string;       // 부서
  author: string;            // 작성자
  draftDate: string;        // 기안일
  items: AdvancePaymentItem[]; // 정산 내역
  approvalLine: ApprovalStep[]; // 결재선
  status: ApprovalStatus;
  approverMemo?: string;
  createdAt: string;
}

export interface WeeklyWorkLog {
  id: string;
  startDate: string;     // 주간 시작일 (YYYY-MM-DD)
  endDate: string;       // 주간 종료일 (YYYY-MM-DD)
  title: string;         // 제목
  author?: string;       // 작성자
  department?: string;   // 부서
  achievementsThisWeek: string; // 금주 실시 사항
  achievementsByDay?: {   // 요일별 실시 사항 (achievementEntriesByDay를 합쳐서 만든 텍스트, 인쇄/엑셀/AI정제용)
    mon?: string;
    tue?: string;
    wed?: string;
    thu?: string;
    fri?: string;
    sat?: string;
    sun?: string;
  };
  achievementEntriesByDay?: {   // 요일별 업무 항목 목록 (하루에 여러 건, 각각 시작~종료 시간 지정 가능)
    mon?: WorkLogDayEntry[];
    tue?: WorkLogDayEntry[];
    wed?: WorkLogDayEntry[];
    thu?: WorkLogDayEntry[];
    fri?: WorkLogDayEntry[];
    sat?: WorkLogDayEntry[];
    sun?: WorkLogDayEntry[];
  };
  plansNextWeek: string;        // 차주 예정 사항
  feedbacks?: string;           // 애로 및 건의 사항/피드백
  contactIds?: string[];  // 연관 거래처/인맥 ID 목록 (명함 ID)
  projectIds?: string[];  // 연관 프로젝트 ID 목록
  expenses?: WorkLogExpense[]; // 비용 추가 항목 리스트
  createdAt: string;
}

// === 전체 문의하기 (Feedback) ===
// [수정] 명함뿐 아니라 앱 전체 어디서나 접수 가능한 문의. 회사별로 나뉘지 않고
// 개발자(운영자)에게 전부 모이는 전역 데이터라서, 다른 데이터처럼 회사 스코프로 나누지 않는다.
export type FeedbackCategory = 'bug' | 'feature' | 'other';

export interface FeedbackItem {
  id: string;
  category: FeedbackCategory;
  content: string;
  authorName?: string;      // 작성자 이름 (로그인 정보 자동 기입)
  authorEmail?: string;      // 작성자 이메일
  authorPhone?: string;      // [수정] 답변/연락을 위해 작성자 핸드폰 번호도 같이 기록 (로그인 정보에 등록되어 있는 경우)
  companyName?: string;      // 작성자 소속 회사명 (개인 계정이면 비어있음)
  pageContext?: string;      // 문의를 남긴 시점의 화면(탭) - 어디서 접수됐는지 참고용
  status: 'new' | 'in_progress' | 'resolved';
  createdAt: string;
}

// === 명함 스캔 초대(바이럴 루프) ===
// [수정] 명함 상세보기에서 "이 분에게 앱 추천하기"를 보낸 기록. 실제 가입 전환까지는
// 추적하지 않고(가입 화면 쪽 파일이 필요해 범위 밖), "누가 몇 명에게 보냈는지" 발송 이력만 기록한다.
export interface InviteRecord {
  id: string;
  contactId?: string;      // 어떤 명함(사람)에게 보냈는지
  contactName?: string;
  channel: 'sms' | 'email' | 'kakao' | 'share' | 'other';
  sentByUserId?: string;
  sentByUserName?: string;
  sentAt: string;
}
