export interface CallRecord {
  id: string;
  contactId: string;
  type: 'incoming' | 'outgoing' | 'missed';
  timestamp: string; // ISO string
  duration?: string; // 예: "3분 45초"
  note?: string; // 통화 내용 요약/메모
}

export interface BusinessCard {
  id: string;
  name: string;
  company: string;
  department: string;
  title: string;
  phoneMobile: string; // 핸드폰
  phoneOffice: string; // 사무실
  phoneOffice2?: string; // 보조 유선전화/직통번호 등 (사무실2)
  phoneFax: string;    // 팩스
  email: string;
  address: string;
  address2?: string;   // 보조 주소 (공장/지사 등 주소가 2개인 경우)
  // [추가] 회사 주소(본사/공장 등)와는 별개로 관리한다. 개인정보라서, 명함 이미지(공유될
  // 수 있는 사진)에는 절대 그려 넣지 않고, 상세보기 화면의 텍스트 정보에만 표시한다.
  homeAddress?: string;
  website?: string;    // 홈페이지 주소
  lat?: number;
  // [추가] 예전엔 주소를 "강남/판교" 같은 동네 이름 몇 개로 대충 찍어서(가짜) 좌표를 항상
  // 채워뒀었다. 그래서 "좌표가 있는지 없는지"만으로는 진짜 지오코딩(카카오 API)으로
  // 정확히 계산된 건지, 예전 가짜값이 그대로 남아있는 건지 구분할 수 없었다. 이 값이
  // true여야 "실제 API로 확인된 정확한 좌표"라는 뜻이다.
  isRealGeocoded?: boolean;
  lng?: number;
  groupId?: string; // [구버전 호환용] 예전에는 그룹 하나만 저장했다. 기존 데이터 호환을 위해 남겨둠.
  // [추가] 명함 하나가 여러 그룹에 동시에 속할 수 있도록 배열로 변경. 새로 저장되는 데이터는
  // 이 필드를 쓴다. groupId(단수)만 있는 예전 데이터는 화면에서 자동으로 [groupId] 취급한다
  // (src/groupUtils.ts의 getContactGroupIds 참고).
  groupIds?: string[];
  frontImage?: string; // base64 data url or sample image
  backImage?: string;
  memo?: string;
  companyInfo?: string; // 회사 간략 요약 정보
  // [수정] 팀/부서별 공유 범위를 위해 이 명함을 누가 등록했는지 기록. isPrivate가 true면
  // 등록한 본인 외에는(같은 회사 소속이라도) 조회 목록에서 보이지 않는다.
  addedByUserId?: string;
  addedByUserName?: string;
  isPrivate?: boolean; // true면 "나만 보기(비공개)" - 등록한 본인에게만 보임
  // [추가] 가져오기(import) 시 사진이 없어서 이름/회사 정보로 자동으로 그려준 명함 이미지인지 표시.
  // true면, 나중에 이름 등을 수정할 때 이 정보를 반영해서 이미지를 자동으로 다시 그려준다.
  // 실제 사진을 촬영/업로드하면 이 값은 false가 되어 더 이상 자동으로 덮어쓰지 않는다.
  isAutoGeneratedImage?: boolean;
  createdAt: string;
  callHistory: CallRecord[];
}

export interface ContactGroup {
  id: string;
  name: string;
  color: string;
  count?: number;
  // [추가] 그룹 자체를 "나만 보기(비공개)"로 설정할 수 있게 한다. 예전엔 명함 하나하나에만
  // 공개/비공개를 정할 수 있어서, 그룹에 새로 들어오는 명함마다 매번 손으로 다시 비공개
  // 처리해야 했고, 그룹 이름 자체(필터 칩, 그룹 관리 목록)는 항상 회사 전체에 보였다.
  // 그룹에 공개 설정을 두면 그룹 자체도 숨길 수 있고, 그 안에 속한 명함도 함께 숨겨진다
  // (명함 각각의 개별 isPrivate 설정과 별개로, 그룹 비공개가 우선 적용된다).
  createdByUserId?: string;
  createdByUserName?: string;
  isPrivate?: boolean; // true면 "나만 보기(비공개)" - 만든 본인에게만 보임
}

export interface ScanCardResult {
  name: string;
  company: string;
  department: string;
  title: string;
  phoneMobile: string;
  phoneOffice: string;
  phoneOffice2?: string;
  phoneFax: string;
  email: string;
  address: string;
  address2?: string;
  memo?: string;
  companyInfo?: string; // 회사 요약 정보
}

export interface ProjectFollowUpAttachment {
  id: string;
  name: string;      // 파일명
  dataUrl: string;   // base64 데이터 (제안서, 견적서 등 첨부파일)
  size?: number;      // 바이트 단위 파일 크기 (표시용)
}

// [추가] "경영지원"/"회계관리" 탭 - 관리자만 볼 수 있는 회사 서류·장부 보관함.
// 서류 종류(근로계약서, 급여명세서 등)마다 필요한 항목이 조금씩 다르지만, 실제로는
// "제목 + 날짜 + 관련자 + 금액(있으면) + 메모 + 첨부파일" 정도로 충분히 다 담을 수 있어서,
// 12개 종류를 전부 따로 만들지 않고 하나의 공용 구조에 category만 다르게 저장한다.
export type AdminDocSection = 'management' | 'accounting';
export type AdminDocCategory =
  // 경영지원
  | 'labor_contract'      // 근로계약서
  | 'salary_agreement'    // 연봉협약서
  | 'employment_cert'     // 재직증명서
  | 'annual_leave_status' // 연차/휴일근무 및 대체 휴가 현황
  | 'power_of_attorney'   // 위임장
  | 'office_supplies'     // 사무실 비품 관리
  | 'sales_contract'      // 영업 계약
  | 'corp_card'           // 법인카드 관리
  | 'cash_flow'           // 현금 흐름 (프로젝트별 INFLOWS/OUTFLOWS + 경비 + 최종 자금흐름)
  // 회계관리
  | 'payslip'             // 급여명세서
  | 'severance'           // 퇴직금 정산
  | 'monthly_cashflow'    // 월별 자금 현황
  | 'bank_withdrawal'     // 통장 출금 내역
  | 'bank_deposit'        // 통장 입금 내역
  | 'loan_repayment'      // 대출 현황
  | 'card_usage'          // 법인카드 사용내역
  | 'advance_payment'     // 가지급내역
  | 'vehicle_fine'        // 차량 과태료 내역
  | 'tax'                 // 각종 세금
  | 'management_fee'      // 관리비내역
  | 'incentive'           // 인센티브 및 명절 상여금
  | 'overseas_trip';      // 해외 출장 경비

export interface AdminDocLineItem {
  id: string;
  label: string;
  amount: number;
  // [추가] 4대보험 공제액 자동계산 기준(과세 대상 급여)에 포함할지 여부. 식대·차량유지비처럼
  // 비과세 항목(일정 한도까지 세금·보험료 계산에서 제외되는 항목)은 false로 둔다.
  // 지급 내역에서만 의미가 있고, 공제 내역에는 안 쓰인다.
  taxable?: boolean;
}

export interface AdminDoc {
  id: string;
  section: AdminDocSection;
  category: AdminDocCategory;
  title: string;          // 제목 (예: "2026년 홍길동 근로계약서")
  date: string;            // 기준 날짜 (YYYY-MM-DD) - 계약일, 지급일, 거래일 등
  personName?: string;     // 관련자/거래처명 (직원명, 카드 소지자, 거래처 등)
  amount?: string;         // 금액 (있는 경우) - 문자열로 저장, 표시할 때 콤마 포맷팅
  memo?: string;
  attachments?: ProjectFollowUpAttachment[]; // 계약서/명세서 등 첨부파일(PDF, 이미지 등)
  createdByUserId?: string;
  createdByUserName?: string;
  createdAt: string;
  // [추가] 급여명세서(category: 'payslip') 전용 구조화 필드. 실제 회사 급여명세서 양식
  // (사원코드/입사일/부서/직위/호봉 + 지급내역·공제내역 각각 여러 줄)을 그대로 담기 위해
  // 다른 서류들과 별도로 필드를 둔다. 급여명세서가 아닌 다른 서류에서는 안 쓰인다.
  payslip?: {
    companyName?: string;
    payMonth?: string;      // 예: "2026-07" (몇 월분 급여인지)
    paymentDate?: string;   // 지급일 (YYYY-MM-DD)
    employeeCode?: string;  // 사원코드
    hireDate?: string;      // 입사일
    department?: string;    // 부서
    position?: string;      // 직위
    salaryGrade?: string;   // 호봉
    // [추가] 4대보험 등 공제율(%). 매년 바뀌는 값이라 화면에서 직접 조정할 수 있게 하고,
    // 이 급여명세서를 저장할 때 그 시점에 쓴 값을 그대로 남겨서, 나중에 요율이 바뀌어도
    // 예전에 발급한 명세서의 계산 근거가 그대로 유지되게 한다(소급 재계산되지 않음).
    rates?: {
      pensionRate: number;     // 국민연금 (기본 4.75%)
      healthRate: number;      // 건강보험 (기본 3.595%)
      ltcRate: number;         // 장기요양보험료 - 건강보험료에 곱하는 비율 (기본 13.14%)
      employmentRate: number;  // 고용보험 (기본 0.9%)
      localTaxRate: number;    // 지방소득세 - 소득세에 곱하는 비율 (기본 10%)
    };
    payItems: AdminDocLineItem[];        // 지급 내역 (기본급, 연장수당, 식대 등)
    deductionItems: AdminDocLineItem[];  // 공제 내역 (국민연금, 건강보험, 소득세 등)
  };
  // [추가] 월별 자금 현황(category: 'monthly_cashflow') 전용 구조화 필드. 통장(계좌)별
  // 이월금/입금/출금을 각각 입력하면 통장잔액은 자동 계산되고, 합계도 자동으로 더해진다.
  cashflow?: {
    periodStart?: string; // 집계 시작일 (YYYY-MM-DD)
    periodEnd?: string;   // 집계 종료일 (YYYY-MM-DD)
    accounts: {
      id: string;
      // [수정] 예전엔 "구분" 한 칸에 은행/계좌/용도를 다 합쳐서 문자열로 적었는데, 이러면
      // 통장 입금/출금 내역과 "같은 통장"인지 프로그램이 알아볼 방법이 없었다. 은행명·
      // 계좌번호를 별도 필드로 분리해서, 같은 은행+계좌를 쓰는 입금/출금 내역과 자동으로
      // 매칭해 금액을 맞출 수 있게 한다.
      bankName?: string;      // 은행 (예: "하나은행")
      accountNumber?: string; // 계좌번호 (예: "110-123-456789")
      subCategory?: string;   // 구분/용도 (예: "급여/외화송금/카드대금")
      broughtForward: number; // 이월금(원) - 전월에서 넘어온 잔액
      deposit: number;        // 입금(원) - 직접 입력하거나 "자동 불러오기"로 입금내역에서 합산
      withdrawal: number;     // 출금(원) - 직접 입력하거나 "자동 불러오기"로 출금내역에서 합산
      note?: string;           // 비고
    }[];
  };
  // [추가] 통장 출금/입금 내역(category: 'bank_withdrawal' | 'bank_deposit') 공용 구조화
  // 필드. 두 카테고리가 "통장(계좌)별로 날짜/프로젝트/금액/거래내용/비고가 여러 줄, 계좌마다
  // 소계, 맨 아래 총합계" 구조로 완전히 똑같아서 하나의 타입을 같이 쓴다.
  bankLedger?: {
    accounts: {
      id: string;
      // [수정] 예전엔 표시 이름(accountName) + 은행/계좌번호가 따로 있어서 입력이 두 번
      // 겹쳤다. 월별 자금 현황과 완전히 똑같이 은행/계좌번호/구분 3칸으로 통일한다 —
      // 이러면 화면 구조도 똑같아지고, 자금 현황과 매칭시킬 때도 헷갈릴 일이 없다.
      bankName?: string;      // 은행 (예: "하나은행")
      accountNumber?: string; // 계좌번호
      subCategory?: string;   // 구분/용도 (예: "급여/외화송금/카드대금")
      entries: {
        id: string;
        date: string;         // 일자 (YYYY-MM-DD)
        project: string;      // 프로젝트 (표시용 이름 - 자유 입력도 허용)
        // [추가] 프로젝트 손익계산서에서 이 입금을 특정 프로젝트의 실제 수입(계약금 등)으로
        // 집계하려면 이름만으로는 프로젝트가 바뀌거나 중복될 때 매칭이 깨진다. 등록된
        // Project.id를 직접 저장해 확실하게 연결한다 - 목록에서 골랐을 때만 채워지고,
        // 직접 입력한 값은 project만 있고 projectId는 없을 수 있다(집계에서 "미매칭"으로 표시).
        projectId?: string;
        amount: number;       // 금액(원)
        description: string;  // 거래내용
        note?: string;         // 비고
        // [추가] 프로젝트 원가계산서(costSheet)의 직접원가/간접원가/일반관리비 항목 중
        // 어디에 해당하는 지출인지 표시. projectId가 같이 있어야 원가계산서 "자동
        // 불러오기"에서 실제로 반영된다 - 프로젝트 연결 없이 이 값만 있어도 아무 효과가
        // 없다(어느 프로젝트 원가인지 알 수 없으므로).
        costCategory?: ProjectCostCategory;
      }[];
    }[];
  };
  // [추가] 대출이자 및 원금 상환 내역(category: 'loan_repayment') 전용 구조화 필드.
  // 대출 건별로 대출금액/이자율/만기/대출잔액/이번 출금(원금+이자)/출금통장을 입력하고,
  // 상환이 끝난 대출은 isRepaid로 표시해서 "상환완료" 구역에 따로 모아 보여준다.
  // [수정] 실제로 회사에서 쓰시는 "대출 현황" 양식에 맞춰 항목을 더 세분화했다: 대출명과
  // 대출계좌를 분리, 이자율을 최초/현재로 분리, 대출일을 추가, 만기일과 납기일을 분리,
  // 출금통장도 은행/계좌로 분리 - 자금현황·통장내역과 동일하게 은행/계좌를 나누는 방식을
  // 따른다.
  loanRepayment?: {
    loans: {
      id: string;
      loanName: string;        // 대출 명 (예: "우리은행_중진직대출")
      loanAccount?: string;    // 대출 계좌
      initialAmount: number;   // 대출 금액(원) - 최초 대출 원금
      initialRate: number;     // 최초 이자율(%)
      currentRate: number;     // 현재 이자율(%)
      loanDate?: string;       // 대출일 (YYYY-MM-DD)
      maturityDate?: string;   // 만기일 (YYYY-MM-DD)
      paymentDay?: string;     // 납기일 (예: "29일")
      balance: number;         // 대출잔액(원) - 현재 남은 원금
      principalPaid: number;   // 출금 금액 - 원금
      interestPaid: number;    // 출금 금액 - 이자 (원금+이자 = 계, 자동 계산)
      withdrawBank?: string;   // 출금 은행
      withdrawAccount?: string; // 출금 계좌
      isRepaid: boolean;       // 상환완료 여부 - 켜면 "상환완료" 구역으로 분류
      repaidDate?: string;     // 상환일 (상환완료인 경우)
      repaidFee?: string;      // 상환수수료 등 메모 (선택)
      note?: string;
    }[];
  };
  // [추가] 법인카드 사용내역(category: 'card_usage') 전용 구조화 필드. 카드(소지자)별로
  // 묶어서 여러 사용 내역(금액/일자/프로젝트명/사용자/비고)을 입력하고, 카드마다 소계,
  // 맨 아래 총계가 자동으로 계산된다. 통장 출금/입금 내역과 구조가 같다.
  cardUsage?: {
    cards: {
      id: string;
      cardName: string;   // 카드명 (예: "국민카드", "하나카드")
      cardNumber?: string; // 카드번호
      holder: string;      // 소지자
      entries: {
        id: string;
        amount: number;    // 사용 금액(원)
        date: string;       // 사용일자 (YYYY-MM-DD)
        project?: string;   // 프로젝트명 (표시용 이름 - 자유 입력도 허용)
        // [추가] 프로젝트 손익계산서 집계용 - 위 bankLedger entries의 projectId와 같은 목적.
        projectId?: string;
        user?: string;      // 사용자 (소지자와 다를 수 있음, 예: 법인카드 대여)
        note?: string;       // 비고
        // [추가] 통합 차량 관리(비용관리/정비일지)·프로젝트·업무일지(일일/주간)에서 이미
        // "법인카드" 결제로 기록된 지출을 "자동 불러오기"로 가져온 경우, 그 원본을
        // 추적하기 위한 값. 사람이 직접 입력한 항목은 이 값이 없다. sourceKey로 같은
        // 원본을 중복으로 다시 가져오지 않도록 막는다.
        sourceKey?: string;
        sourceLabel?: string; // 화면에 보여줄 원본 이름 (예: "차량 비용관리")
        // [추가] 위 bankLedger entries의 costCategory와 같은 목적 - 프로젝트 원가계산서
        // 항목 자동 불러오기에 쓰인다. projectId가 같이 있어야 반영된다.
        costCategory?: ProjectCostCategory;
      }[];
    }[];
  };
  // [추가] 회계관리 > 가지급내역(category: 'advance_payment') 전용 구조화 필드. 공유해주신
  // "2026년도 월별 가지급 내역" 양식과 동일하게, 인원(열) × 월(행)의 표로 관리한다.
  // 인원은 회사 상황에 따라 바뀔 수 있어 자유롭게 추가/삭제 가능한 목록으로 둔다(이름만 있으면
  // 어떤 인원이든 열로 추가 가능 - 특정 인원 이름을 코드에 고정하지 않음). 카이저합계(그 달
  // 전체 합)와 맨 아래 합계 행은 입력값 기준으로 화면에서 자동 계산되어 항상 정확하다.
  advancePayment?: {
    people: { id: string; name: string }[]; // 표의 열 - 인원
    months: {
      id: string;
      monthKey: string;   // YYYY-MM (전자결재 자동 불러오기 매칭 기준)
      label: string;       // 화면에 보여줄 구분 텍스트 (기본 "01월" 등, 자유 편집 가능)
      depositDate?: string; // 입금일
      // [추가] 인원별 이번 달 금액. manual은 직접 입력, imported는 전자결재 > 가지급금
      // 정산서가 승인되면 "자동 불러오기"로 채워진 항목들 - 둘을 더한 값이 그 칸의 최종
      // 금액이다. imported의 sourceKey로 같은 정산서 항목을 중복으로 다시 가져오지 않는다.
      amounts: Record<string, {
        manual: number;
        imported: { sourceKey: string; sourceLabel: string; amount: number }[];
      }>;
      note?: string; // 비고 (계산식 메모 등 자유 텍스트, 공유해주신 양식처럼 길게 적어도 됨)
    }[];
  };
  // [수정] 회계관리 > 차량 과태료 내역(category: 'vehicle_fine') 전용 구조화 필드. 공유해주신
  // "2026년 법인차량 과태료 내역" 양식과 동일한 열 구성(위반일자/위반차량/금액/처리일자/
  // 내용/비고)으로 맞췄다 - 원래는 "납부여부" 체크박스만 뒀는데, 실제 양식엔 언제 처리했는지
  // 날짜(처리일자)가 있고 비고엔 담당자 이름을 적는 방식이라 그대로 반영했다.
  vehicleFine?: {
    entries: {
      id: string;
      date: string;          // 위반일자
      vehicle: string;        // 위반차량 (번호/명)
      amount: number;         // 금액(원)
      processedDate?: string; // 처리일자 (비어있으면 아직 미처리)
      detail: string;          // 내용 (위반 상세)
      note?: string;            // 비고 (담당자 이름 등 자유 기재)
      // [추가] 회계관리 > 통장 출금 내역에서 "자동 불러오기"로 가져온 경우, 그 원본을
      // 추적하기 위한 값. 사람이 직접 입력한 항목은 이 값이 없다. sourceKey로 같은
      // 원본을 중복으로 다시 가져오지 않도록 막는다.
      sourceKey?: string;
      sourceLabel?: string; // 화면에 보여줄 원본 이름 (예: "통장 출금 내역")
    }[];
  };
  // [수정] 회계관리 > 각종 세금(category: 'tax') 전용 구조화 필드. 공유해주신
  // "2026년 각종 세금 내역" 양식과 동일하게 no(자동 순번)/내역/결재일자/금액/비고로
  // 단순화했다 - 원래 세목/귀속기간/신고기한/납부여부를 따로 뒀는데, 실제 양식은 "내역"
  // 한 칸에 다 적고("부가가치세(26년1기분)" 처럼) 비고엔 "완료" 같은 상태만 적는 방식이라
  // 그대로 반영했다. 결재일자는 "없음.", "2026.04.24완료"처럼 날짜가 아닌 텍스트가 섞여
  // 있는 경우가 있어 날짜 타입이 아닌 자유 텍스트로 둔다.
  taxPayment?: {
    entries: {
      id: string;
      description: string;  // 내역
      paidDate?: string;      // 결재일자 (자유 텍스트 - 날짜가 아닌 메모가 섞일 수 있음)
      amount: number;         // 금액(원)
      note?: string;           // 비고 (완료 여부 등)
      // [추가] 통장 출금 내역에서 "자동 불러오기"로 가져온 경우의 원본 추적용.
      sourceKey?: string;
      sourceLabel?: string;
    }[];
  };
  // [추가] 회계관리 > 관리비내역(category: 'management_fee') 전용 구조화 필드. 공유해주신
  // "월별 관리비내역" 양식과 동일하게 호실(열) × 월(행) 표로 관리한다 - 가지급내역과 완전히
  // 같은 구조라서(호실 = 인원 자리), 호실도 회사 상황에 따라 바뀔 수 있어 자유롭게
  // 추가/삭제 가능한 목록으로 둔다. 통장 출금 내역에서 "자동 불러오기"로 채워 넣을 수 있다.
  managementFee?: {
    units: { id: string; name: string }[]; // 표의 열 - 호실(예: "518호")
    months: {
      id: string;
      monthKey: string;   // YYYY-MM
      label: string;        // 화면에 보여줄 구분 텍스트 (기본 "01월" 등)
      paymentDate?: string; // 납부일
      amounts: Record<string, {
        manual: number;
        imported: { sourceKey: string; sourceLabel: string; amount: number }[];
      }>;
      note?: string;
    }[];
  };
  // [추가] 회계관리 > 인센티브(상여금)(category: 'incentive') 전용 구조화 필드. 공유해주신
  // "인센티브 및 명절 상여금" 양식과 동일하게 일자/금액/지급 내역/지급 대상자/비고 열로
  // 건별 여러 줄을 입력하는 단순한 표다 - 차량 과태료 내역, 각종 세금과 같은 구조.
  incentive?: {
    entries: {
      id: string;
      date: string;               // 일자
      amount: number;              // 금액(원)
      // [수정] 지급 내역 - 화면에는 "현금/상품권/선물/신용카드/기타/직접 입력" 순서로
      // 고르는 드롭다운이지만, "직접 입력"을 고르면 자유 텍스트를 쓸 수 있어야 해서
      // 저장 타입은 고정된 값 목록이 아니라 자유 문자열로 둔다.
      method: string;               // 지급 내역 (예: "현금", "상품권", 또는 직접 입력한 값)
      description: string;         // 지급 대상자 (예: "박현용")
      note?: string;                 // 비고
    }[];
  };
  // [추가] 회계관리 > 해외 출장 경비(category: 'overseas_trip') 전용 구조화 필드. 공유해주신
  // "해외 출장 경비 사용내역" 양식과 동일하게 일자/금액/사용구분(항공료·숙박비·식비·교통비·
  // 환전 비용·직원 선물·기타)/사용내역/사용자/지급방법/지급구분/비고 열로 건별 여러 줄을
  // 입력한다. 출장 하나 = 문서(AdminDoc) 하나로 저장해서, 개별 출장 건별로도 확인하고
  // 여러 출장을 연도별로 합쳐서도 확인할 수 있게 한다(차량 과태료 내역과 동일한 방식).
  overseasTrip?: {
    entries: {
      id: string;
      date: string;               // 일자(결제일) - 실제로 카드 결제/현금 지출한 날짜 그대로
      // [추가] 귀속연도 - 전시회 등 출장 일정이 다음 해라서 항공권 등을 그 전 해에 미리
      // 결제하는 경우, 실제 결제일(date)과 이 경비를 어느 해 출장 경비로 잡을지(귀속연도)가
      // 달라진다. 예: 2026년 3월 전시회 항공권을 2025년 12월에 결제 → date는
      // "2025-12-10"으로 실제 결제일을 그대로 남기고, fiscalYear는 "2026"으로 지정해서
      // 2026년 해외 출장 경비로 집계되게 한다. 비워두면(대부분의 경우) date의 연도를
      // 그대로 귀속연도로 쓴다 - 연도별로 한 페이지로 보기/연도 목록도 이 값 기준으로 모은다.
      fiscalYear?: string;         // 귀속연도 (YYYY, 비어있으면 date의 연도)
      amount: number;              // 금액(원)
      // 사용구분 - 화면에는 "항공료/숙박비/식비/교통비/환전 비용/직원 선물/기타/직접 입력"
      // 순서로 고르는 드롭다운이지만, "직접 입력"을 고르면 자유 텍스트를 쓸 수 있어야 해서
      // 저장 타입은 고정된 값 목록이 아니라 자유 문자열로 둔다.
      category: string;            // 사용구분 (예: "항공료", 또는 직접 입력한 값)
      description: string;        // 사용내역 (구체적 내용, 예: "인천-도쿄 왕복")
      user: string;                // 사용자
      // 지급방법 - "신용카드/현금/직접 입력" 드롭다운, category와 동일한 방식.
      payMethod: string;            // 지급방법 (예: "신용카드")
      payDetail?: string;          // 지급구분 (예: 카드명 - 자유 입력, 자동완성 제공)
      note?: string;                // 비고
      // [추가] 카드사용내역/업무일지(법인카드 결제) 또는 통장 출금 내역(환전 비용·현금
      // 지급)에서 "자동 불러오기"로 가져온 경우, 그 원본을 추적하기 위한 값. 사람이 직접
      // 입력한 항목은 이 값이 없다. sourceKey로 같은 원본을 중복으로 다시 가져오지 않는다.
      sourceKey?: string;
      sourceLabel?: string; // 화면에 보여줄 원본 이름 (예: "카드사용내역", "업무일지(일일)", "통장 출금 내역")
    }[];
  };
  // [추가] 경영지원 > 법인카드 관리(category: 'corp_card') 전용 구조화 필드. 카드사용내역
  // (거래 단위 상세 내역)과 달리, 이건 "카드별로 이번 달 얼마 썼는지" 월 단위 요약 표다.
  // 카드 한 장 = 한 줄.
  corpCard?: {
    yearMonth?: string; // 대상 연월 (예: "2026-07")
    cards: {
      id: string;
      cardCompany: string;    // 카드사 (예: "국민카드")
      cardNumber: string;      // 카드번호
      expiry?: string;         // 유효기간 (MM/YY)
      user: string;            // 사용자
      periodLabel?: string;    // 사용일수 (예: "전월 01일~전월 말일")
      paymentDay?: string;     // 출금일자 (예: "15일")
      amount: number;          // 금액(원)
      withdrawBank?: string;   // 출금은행
      withdrawAccount?: string;// 출금계좌
      note?: string;            // 비고
    }[];
  };
  // [추가] 경영지원 > 현금 흐름(category: 'cash_flow') 전용 구조화 필드. "연도 하나 = 문서
  // 하나"로 저장하고, 그 안에 INFLOWS(프로젝트별 수금)/OUTFLOWS(프로젝트별 매입)/경비
  // (급여·사업경비·부채·기타경비)를 월별로 입력해두면, "현금 흐름 최종"(매입+경비 합계,
  // 순현금흐름, 통장잔고)은 화면에서 자동으로 계산해서 보여준다(따로 입력하지 않음).
  cashFlowAnnual?: {
    year: string;               // 대상 연도 (예: "2026")
    openingBalance: number;     // 전년도이월금 (연초 통장잔고 - 1월 통장잔고 계산의 시작값)
    // INFLOWS(수금) - 프로젝트별 한 줄. "기타 매출" 등 프로젝트명이 없는 합산 줄도 그냥
    // 이름만 채워서 같은 목록에 추가하면 된다.
    inflows: {
      id: string;
      name: string;             // 프로젝트명
      recipient?: string;       // 프로젝트 수주자
      contractAmount?: number;  // 계약금(VAT포함)
      remainingAmount?: number; // 잔여기성
      prevYear?: number;        // 전년도(이월 수금액)
      // '1'~'12' 키, 월별 셀. 직접 입력(manual)과 통장 입금 내역에서 "자동 불러오기"로
      // 채워 넣은 금액(imported)을 둘 다 더해서 그 달 금액이 된다(관리비내역과 동일한 방식).
      months: Record<string, { manual: number; imported: { sourceKey: string; sourceLabel: string; amount: number }[] }>;
    }[];
    // OUTFLOWS(매입) - 프로젝트별 물품 매입처 한 줄.
    outflows: {
      id: string;
      name: string;             // 프로젝트별 물품 매입처
      recipient?: string;       // 프로젝트 수주자
      estimatedTotal?: number;  // 예상물품구입(외주)총액
      note?: string;             // 비고
      prevYear?: number;        // 전년도 구입
      // '1'~'12' 키, 월별 셀. 직접 입력(manual) + 통장 출금 내역에서 자동 불러온 금액(imported).
      months: Record<string, { manual: number; imported: { sourceKey: string; sourceLabel: string; amount: number }[] }>;
    }[];
    // 경비 - "급여/소득공제", "사업 경비", "부채", "기타 경비" 네 그룹으로 나누고, 그룹
    // 안에서 항목을 자유롭게 추가/삭제할 수 있다.
    expenseGroups: {
      id: string;
      name: string;              // 그룹명 (예: "급여/소득공제")
      items: {
        id: string;
        label: string;           // 항목명 (예: "급여", "4대보험(퇴직연금/보)")
        initialAmount?: number;  // 부채 항목 등에서 참고용 최초 금액(선택, 없으면 미표시)
        // '1'~'12' 키, 월별 셀. 직접 입력(manual) + 통장 출금 내역에서 자동 불러온 금액(imported).
        months: Record<string, { manual: number; imported: { sourceKey: string; sourceLabel: string; amount: number }[] }>;
      }[];
    }[];
  };
  // [추가] 경영지원 > 근로계약서(category: 'labor_contract') 전용 구조화 필드. 회사에서
  // 실제 쓰시는 계약서 양식(공유해주신 PDF)을 그대로 재현한다. 근로시간/연차/퇴직 규정 등
  // 고정 조항은 인쇄 화면에 그대로 박혀있고, 사람마다 바뀌는 항목만 여기 채운다.
  laborContract?: {
    // [추가] 회사(사용자) 쪽 정보 중 사업종류·주소는 로그인 계정 프로필에 없는 값이라
    // (회사명/대표자/사업자등록번호는 계정 정보에서 자동으로 가져오지만) 여기서 직접
    // 입력받는다. 한번 입력해두면 이 문서에 그대로 저장된다.
    companyBusinessType?: string; // 사업 종류 (예: "제조업")
    companyAddress?: string;      // 사업체 주소
    employeeName?: string;       // 근로자 성명
    employeeBirthDate?: string;  // 생년월일 (YYYY-MM-DD)
    employeeAddress?: string;    // 근로자 주소
    employmentType?: 'regular' | 'contract' | 'intern'; // 고용형태 (정규직/계약직/인턴)
    // [추가] 연봉협약서(category: 'salary_agreement') 전용 - 공유해주신 "연봉 계약서" 실제
    // 양식(인적 사항 및 근무 정보 표)에 맞춰 추가한 필드. 근로계약서(labor_contract)에서는
    // 쓰지 않는다.
    hireDate?: string;           // 입사일 (YYYY-MM-DD)
    department?: string;         // 소속
    position?: string;           // 현재직급
    salaryItems: AdminDocLineItem[]; // 급여 구성 항목 (기본급/연장근로수당/차량유지비/식대 등)
    contractStartDate?: string;  // 계약 시작일
    contractEndDate?: string;    // 계약 종료일 (정규직 등 기간 정함이 없으면 비워둠)
    workLocation?: string;       // 근무 장소
    jobDuties?: string;          // 담당 업무
    contractDate?: string;       // 계약서 작성일(맨 아래 서명 날짜)
  };
  // [추가] 경영지원 > 재직증명서(category: 'employment_cert') 전용 구조화 필드.
  // 공유해주신 실제 양식(테두리 박스 + 구분선 아래 발급번호/직인 영역)을 그대로 재현한다.
  employmentCert?: {
    companyAddress?: string;      // 사업체 주소
    employeeAddress?: string;     // 재직자 주소
    employeeName?: string;        // 성명
    residentNumberMasked?: string; // 주민등록번호 (뒷자리 마스킹, 예: "000000-0******")
    hireDate?: string;            // 입사일
    purpose?: string;             // 용도 (예: "제출용")
    submitTo?: string;            // 제출처 (예: "노원구청")
    applicationDate?: string;     // 신청일
    department?: string;          // 소속
    position?: string;            // 직위
    documentNumber?: string;      // 문서번호 (예: "제 2026-0001호")
    issueDate?: string;           // 증명 발급일
  };
  // [추가] 경영지원 > 연차 현황(category: 'annual_leave_status') 전용 구조화 필드. 공유해주신
  // "OOOO년 연차 / 휴일근무 및 대체 휴가" 양식과 동일하게, 연도 하나 = 문서 하나로 저장하고
  // 그 안에 직원별로 (1) 연차 사용 내역, (2) 휴일(초과) 근무, (3) 대체휴가 세 목록을 각각
  // 여러 줄 입력한다(현금 흐름의 "연도 하나 = 문서 하나" 방식과 동일). 총 년차일수/잔여일수는
  // 사람마다 한 번만 있고, 사용/휴일근무/대체휴가는 각각 여러 건일 수 있다.
  annualLeaveStatus?: {
    year: string; // 대상 연도 (예: "2026")
    people: {
      id: string;
      name: string;                 // 이름
      hireDate?: string;            // 입사일자
      // 총 년차일수 - 전자결재 > 휴가 신청서에서 이미 사람마다 관리하고 있는 값(총 부여
      // 연차일수)과 같은 개념. "전자결재에서 불러오기"를 쓰면 그 사람의 최근 승인된 연차
      // 신청서에 적힌 값을 그대로 가져와 채워준다(직접 수정도 가능).
      totalAnnualDays: number;
      // 연차 사용 내역 - 휴가일/사용연차일수/비고. "전자결재에서 불러오기"로 승인된 연차
      // 신청서를 그대로 가져올 수 있다(가져온 항목은 sourceKey로 표시되어 중복으로 다시
      // 가져오지 않는다).
      leaveEntries: {
        id: string;
        startDate: string;           // 휴가 시작일
        endDate?: string;             // 휴가 종료일 (하루짜리면 비워두거나 startDate와 동일)
        days: number;                  // 사용연차일수
        note: string;                  // 비고 (예: "전체년차", "장모님기일" 등 사유)
        sourceKey?: string;
        sourceLabel?: string; // 예: "전자결재 휴가 신청서"
      }[];
      // 휴일(초과) 근무 - 일자/기간(일)/시간/현장. 전자결재와 연동되는 데이터가 따로 없어
      // 직접 입력으로만 관리한다.
      overtimeEntries: {
        id: string;
        date: string;      // 일자
        periodDays?: number; // 기간(일)
        hours?: number;      // 시간
        site?: string;        // 현장
        note?: string;         // 비고 (예: "휴일근무 근무수당지급완료(04.30)")
      }[];
      // 대체휴가 - 사용일 + 비고(예: "20일 대체휴가_정리완료"). 직접 입력으로만 관리한다.
      substituteEntries: {
        id: string;
        date: string;
        note?: string;
      }[];
    }[];
  };
  // [추가] 경영지원 > 위임장(category: 'power_of_attorney') 전용 구조화 필드. 공유해주신
  // 양식을 그대로 재현한다 - 위임받는 사람의 정보와 위임 업무 내용만 채우면 된다.
  powerOfAttorney?: {
    employeeAddress?: string;      // 위임받는 사람 주소
    employeeName?: string;         // 위임받는 사람 성명
    residentNumberMasked?: string; // 주민등록번호 (마스킹)
    purpose?: string;              // 용도 (예: "법인지점 통장 개설")
    submitTo?: string;             // 제출처 (예: "하나은행")
    taskDescription?: string;      // 위임 업무 내용 (예: "법인통장 개설")
    issueDate?: string;            // 작성일자
  };
  // [추가] 경영지원 > 영업 계약(category: 'sales_contract') 전용 구조화 필드. 공유해주신
  // "영업 개발(수요업체 발굴) 자문 계약서" 18개 조항 전문을 그대로 재현하고, 거래처(갑)
  // 정보·계약기간·수수료 구조처럼 계약마다 달라지는 항목만 입력받는다. 첨부되는 원가계산서/
  // 손익계산서/보수율계산표/사업자등록증은 계약마다 내용이 다른 별도 서류라 이 문서 자체의
  // "첨부파일" 기능으로 업로드해서 붙이는 방식을 쓴다(계산기로 자동 생성하지 않음).
  salesContract?: {
    counterpartyName?: string;      // 갑(영업 자문사) 상호
    counterpartyAddress?: string;   // 갑 주소
    counterpartyBizNumber?: string; // 갑 사업자등록번호
    counterpartyRepName?: string;   // 갑 대표이사
    contractDate?: string;          // 계약일자
    contractStartDate?: string;     // 계약 시작일
    contractEndDate?: string;       // 계약 종료일
    feeTier1Max?: number;           // 1구간 매출 상한(원) - 예: 1,800,000,000 (18억)
    feeTier1Rate?: number;          // 1구간 수수료율(%) - 예: 5
    feeTier2Max?: number;           // 2구간 매출 상한(원) - 예: 3,000,000,000 (30억)
    feeTier2Rate?: number;          // 2구간 수수료율(%) - 예: 4
    feeTier3Rate?: number;          // 3구간(2구간 초과분) 수수료율(%) - 예: 3
    lowProfitThreshold?: number;    // 경상이익률 기준(%) - 예: 20 (미만이면 아래 요율 적용)
    lowProfitRate?: number;         // 경상이익률 기준 미만일 때 경상이익 대비 수수료율(%) - 예: 20
    aftercareCapRate?: number;      // 사후관리비용 한도(매출액 대비 %) - 예: 3
    recognitionMonths?: number;     // 후속 매출 보수 인정 기간(개월) - 예: 24
    recognitionCapAmount?: number;  // 후속 매출 보수 인정 누적 매출 한도(원) - 예: 2,000,000,000 (20억)
  };
  // [추가] 회계관리 > 퇴직금 정산(category: 'severance') 전용 구조화 필드. 공유해주신
  // "퇴직금 중간정산 지급명세서" 양식을 그대로 재현한다.
  severance?: {
    employeeName?: string;         // 신청인
    residentNumberMasked?: string; // 주민번호 (마스킹)
    hireYearMonth?: string;        // 입사년월 (YYYY-MM)
    periodStart?: string;          // 중간정산 대상기간 시작
    periodEnd?: string;            // 중간정산 대상기간 종료
    reason?: string;               // 중간정산 사유
    companyAdvanceAmount?: number; // ① 회사 선지급 금액
    companyAdvanceDate?: string;   // ① 회사 선지급 일자
    companyAdvanceBank?: string;   // ① 입금 은행
    bankAccrualAmount?: number;    // ② 은행 적립금(퇴직연금 등) 금액
    receiveDate?: string;          // 수령일(서명 날짜)
  };
}

export interface MeetingExpenseItem {
  id: string;
  category: 'meal' | 'drinks' | 'purchase' | 'service_fee' | 'custom'; // 식대 / 음료(커피) / 물품 구입 / 식사 서비스 비용 / 직접 입력
  categoryCustom?: string; // 직접 입력 시 카테고리명
  amount: number;
  payMethod: 'company_card' | 'personal_card' | 'cash'; // 법인(회사)카드 / 개인카드 / 현금
  memo?: string; // 지출 상세 사유/메모
  receiptImage?: string; // 스캔하거나 첨부한 영수증 사진 (base64)
}

export interface ProjectFollowUp {
  id: string;
  projectId: string;
  content: string;
  date: string;
  status: 'planned' | 'in_progress' | 'done';
  meetingDegree?: number;   // 1차 미팅, 2차 미팅 등 차수 (제한 없음, 비워두면 '업무 기록'으로 표시)
  meetingType?: 'meeting' | 'followup'; // 같은 차수 안에서 "미팅"인지 "팔로우업"인지 구분
  attendee?: string;       // 미팅 참여 담당자 (미팅자, 거래처/고객 측)
  internalStaffName?: string; // 우리 회사 담당 직원 (같은 회사로 가입한 계정 중 선택)
  hasVoice?: boolean;      // 음성 메모 녹음 여부
  voiceUrl?: string;       // 음성 재생용 (시뮬레이션 혹은 실제 녹음 데이터)
  voiceDuration?: string;  // 음성 녹음 분초 (예: "0:15")
  attachments?: ProjectFollowUpAttachment[]; // 제안서/견적서/발송자료 등 첨부파일
  expenses?: MeetingExpenseItem[]; // 미팅/팔로우업 관련 지출 비용 (영수증 스캔 포함)
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  salesRep?: string;           // 영업자(담당자) - 이 프로젝트를 등록/담당하는 내부 영업 담당자 (기본값: 등록자 본인)
  developer?: string;          // 시행사(발주처). [수정] 최종고객(발주처, endCustomer)와 같은
                                // 개념이라 등록/수정 폼에서는 별도 입력칸 없이 항상 endCustomer
                                // 값을 그대로 미러링해서 저장한다(카드 뱃지·거래처 회사명 매칭
                                // 등 기존에 이 필드를 참조하던 기능과의 하위호환용으로만 남겨둠).
  contractor?: string;         // 시공사
  architect?: string;          // 건축설계사
  interiorDesigner?: string;   // 인테리어설계사
  electricalDesigner?: string; // 전기설계사
  mechanicalDesigner?: string; // 기계설계사
  supervisor?: string;         // 감리사
  operator?: string;           // 운영사
  status: 'opportunity' | 'progress' | 'completed' | 'failed';
  priority: 'high' | 'medium' | 'low';
  dueDate: string;
  contactIds: string[]; // 연관된 거래처 명함 ID 목록
  budget?: string;
  followUps: ProjectFollowUp[];
  createdAt: string;
  // [추가] "프로젝트 파이프라인" 양식(번호/프로젝트명/영업자/최종고객/현장·지역/제품군/
  // 주요품목·사양/예상 수주금액/예상 수주시기/성사확률/가중 예상금액(자동계산)/진행단계/
  // 경쟁사/ABB 지원요청/비고)에 맞춰 프로젝트 리스트 출력(화면 표·인쇄·엑셀)을 이 형식으로
  // 바꾸면서 추가된 영업 파이프라인 관리용 필드들. 기존 시행사/시공사/설계사 등 필드나
  // status(칸반 진행 상태)와는 별개로, 이 회사의 영업 파이프라인 보고 양식 전용으로 쓰인다.
  endCustomer?: string;   // 최종고객(발주처)
  siteLocation?: string;  // 현장/지역
  productGroup?: string;  // 제품군(PG)
  mainItemsSpec?: string; // 주요 품목·사양
  expectedTiming?: string; // 예상 수주시기 (예: "2026 Q3", "미정" - 날짜가 아닌 자유 텍스트)
  winProbability?: number; // 성사확률(%) 0~100. 가중 예상금액(budget × winProbability/100)은
                            // 항상 이 값과 budget에서 계산해서 보여주며 별도로 저장하지 않는다.
  // 파이프라인 단계(발굴/견적/협상/수주예정/보류). 프로젝트 관리용 status(기회/진행/완료/실패)와는
  // 별개의 값으로, 리스트 출력에서는 이 값을 "진행단계" 칸에 쓴다.
  pipelineStage?: 'lead' | 'quotation' | 'negotiation' | 'closing' | 'hold';
  competitor?: string;    // 경쟁사
  supportNeeded?: string; // ABB 지원요청
  remarks?: string;       // 비고 (리스트 출력 전용 - 메모(description)와는 별개 칸)
  // [추가] 프로젝트 탭 > "프로젝트 원가계산서" 서브탭 전용 데이터. 공유해주신 "프로젝트 원가
  // 계산서" 양식(매출액/직접원가/간접원가/일반관리비/사후관리비용을 항목별로 직접 입력하면
  // 소계·총원가·경상이익·경상이익율을 자동 계산)을 그대로 반영한다. 프로젝트 하나에 원가
  // 계산서 하나가 매칭되는 구조라 별도 컬렉션으로 안 빼고 Project 안에 그대로 둔다 - 기존
  // 프로젝트 CRUD API(PUT /api/projects/:id가 body를 그대로 병합 저장)를 그대로 재사용할
  // 수 있어서 서버 쪽 변경 없이 구현 가능하다.
  costSheet?: ProjectCostSheet;
}

// [추가] 프로젝트 원가계산서의 직접원가/간접원가/일반관리비 세부 항목을 통장 출금내역·
// 카드사용내역 거래에서 "자동 불러오기"로 채워 넣을 수 있게 하기 위한 항목 키 목록.
// 거래 항목에 이 값 중 하나를 태그해두면(costCategory, AdminDoc.bankLedger/cardUsage
// entries 참고) 원가계산서에서 프로젝트+항목이 일치하는 거래를 찾아 자동으로 가져온다.
export type ProjectCostCategory =
  | 'rawMaterialCost' | 'outsourcingCost' | 'directLaborCost' | 'directExpense'
  | 'indirectLaborCost' | 'depreciationCost' | 'qualityControlCost' | 'logisticsCost'
  | 'laborAllocationCost' | 'rentCost' | 'commsItCost' | 'legalAccountingCost' | 'otherAdminCost';

// 화면(거래 항목 태그 드롭다운, 원가계산서 자동 불러오기 요약 등)에 공통으로 쓰는 한글
// 이름 - 한 곳에서만 관리해서 두 화면(AdminDocsView/ProjectsView)의 이름이 어긋나지
// 않게 한다.
export const PROJECT_COST_CATEGORY_LABELS: Record<ProjectCostCategory, string> = {
  rawMaterialCost: '원재료비',
  outsourcingCost: '외주 가공비',
  directLaborCost: '직접 노무비',
  directExpense: '직접 경비',
  indirectLaborCost: '간접 노무비',
  depreciationCost: '감가상각비',
  qualityControlCost: '품질 관리비',
  logisticsCost: '물류, 보관비',
  laborAllocationCost: '인건비 배부',
  rentCost: '임차료',
  commsItCost: '통신, 전산비',
  legalAccountingCost: '법무, 회계비',
  otherAdminCost: '기타 관리비'
};

// 원가계산서 양식에 나오는 순서 그대로 - 드롭다운/자동 불러오기 요약에서 이 순서로 보여준다.
export const PROJECT_COST_CATEGORY_ORDER: ProjectCostCategory[] = [
  'rawMaterialCost', 'outsourcingCost', 'directLaborCost', 'directExpense',
  'indirectLaborCost', 'depreciationCost', 'qualityControlCost', 'logisticsCost',
  'laborAllocationCost', 'rentCost', 'commsItCost', 'legalAccountingCost', 'otherAdminCost'
];

// [추가] 위 13개 항목의 실제 저장 값 - 관리비내역/가지급내역과 동일하게 manual(직접 입력)
// + imported(통장 출금내역·카드사용내역에서 자동 불러온 값, sourceKey로 중복 방지)를
// 더한 값이 최종 금액이다. 이렇게 해야 "자동 불러오기"를 다시 눌러도 이미 직접 입력해둔
// 값을 덮어쓰지 않고, 새로 태그된 거래만 추가로 더해진다.
export interface ProjectCostSheetAmount {
  manual: number;
  imported: { sourceKey: string; sourceLabel: string; amount: number }[];
}

// [추가] 위 Project.costSheet의 실제 타입 - "프로젝트 원가 계산서" 양식 그대로.
export interface ProjectCostSheet {
  // 상단 기본 정보. Project 자체에도 비슷한 필드(endCustomer/dueDate 등)가 있지만, 원가
  // 계산서는 "정식 계약서 기준" 값을 별도로 관리하는 문서라 독립된 값으로 둔다 - 처음 열 때만
  // Project 값으로 미리 채워주고, 그 뒤로는 서로 영향을 주지 않는다.
  orderer?: string;            // 발주처
  contractNumber?: string;     // 계약번호
  contractDate?: string;       // 계약일자 (YYYY-MM-DD)
  deliveryDeadline?: string;   // 납품기한 (YYYY-MM-DD)
  preparedDate?: string;       // 작성일 (YYYY-MM-DD)
  preparedDept?: string;       // 작성부서

  // 매출액
  contractRevenue: number;     // 계약 매출액(원)
  additionalRevenue: number;   // 추가 매출액(원)

  // 직접원가 (소계 B) - 통장 출금내역·카드사용내역에서 "자동 불러오기"로 채울 수 있어
  // manual(직접 입력)+imported(자동 반영) 구조다. 예전에 저장된 문서는 이 값이 그냥
  // 숫자(number)일 수 있으니, 읽는 쪽(csFieldTotal)에서 두 형태를 모두 다룬다.
  rawMaterialCost: ProjectCostSheetAmount;     // 원재료비 - 자재 BOM 기준
  outsourcingCost: ProjectCostSheetAmount;     // 외주 가공비 - 제작, 조립, 가공 등
  directLaborCost: ProjectCostSheetAmount;     // 직접 노무비 - 투입 인원 × 공수
  directExpense: ProjectCostSheetAmount;       // 직접 경비 - 운송, 설치, 시운전 등

  // 간접원가 (소계 C)
  indirectLaborCost: ProjectCostSheetAmount;   // 간접 노무비 - 관리, 기술 지원 인력 등
  depreciationCost: ProjectCostSheetAmount;    // 감가상각비 - 장비, 금형 등
  qualityControlCost: ProjectCostSheetAmount;  // 품질 관리비 - 검사, 시험 등
  logisticsCost: ProjectCostSheetAmount;       // 물류, 보관비 - 창고, 운송 등

  // 일반관리비 (소계 D)
  laborAllocationCost: ProjectCostSheetAmount; // 인건비 배부 - 관리부서
  rentCost: ProjectCostSheetAmount;            // 임차료 - 사무실, 공장
  commsItCost: ProjectCostSheetAmount;         // 통신, 전산비 - 시스템
  legalAccountingCost: ProjectCostSheetAmount; // 법무, 회계비 - 외주
  otherAdminCost: ProjectCostSheetAmount;      // 기타 관리비

  // 사후관리비용. "예상 사후 관리비"(매출액×5%)와 "사후 관리비 한도"(매출액×6%)는 매출액
  // 합계(A)에서 자동 계산되는 참고값이라 따로 저장하지 않고 화면에서 그때그때 계산한다.
  // 실제로 총원가에 반영되는 값(적용(E))만 직접 입력/조정하도록 저장한다.
  appliedPostSalesCost: number; // 적용 사후 관리비 = 적용(E)

  // 비고 - 양식에 기본 문구가 있는 3개 행만 별도 필드로 관리(나머지 행은 비고 없음)
  contractRevenueNote?: string;  // 계약 매출액 행 비고 (기본값 "VAT 별도")
  totalRevenueNote?: string;     // 합계(A) 행 비고 (기본값 "손익 기준")
  appliedPostSalesNote?: string; // 적용(E) 행 비고 (기본값 "낮은 금액 적용")
}

export interface MyProfile {
  name: string;
  company: string;
  department: string;
  title: string;
  phoneMobile: string;
  phoneOffice: string;
  phoneFax: string;
  email: string;
  address: string;
  snsUrl?: string;
  website?: string;
  memo?: string;
  // [수정] 내 명함 앞/뒷면 스캔 사진을 프로필과 함께 저장/조회할 수 있도록 추가
  // (기존에는 이 필드가 없어서 촬영한 사진이 AI 인식에만 잠깐 쓰이고 저장되지 않았음)
  frontImage?: string; // base64 data url
  backImage?: string;  // base64 data url
  // [수정] 공유용 랜딩 페이지(/s/:slug)에 쓰이는 공개 식별자. 최초 조회 시 서버가 자동 생성해서 저장한다.
  shareSlug?: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  type: 'individual' | 'company';
  companyName?: string;
  businessNumber?: string;
  // [수정] 운영 현황에서 가입자 연락처를 확인할 수 있도록 (선택 입력)
  phone?: string;
  // [수정] 코드 곳곳에서 이미 사용 중이었는데 타입 선언이 빠져있던 필드들
  // (직책 / 회사 내 역할). 회사(type: 'company') 회원에게만 의미가 있다.
  position?: string;
  role?: 'admin' | 'member';
  // [추가] 회사 회원가입 승인 상태. 같은 사업자번호로 가입하는 두 번째 이후 사용자는
  // 'pending'으로 시작해서, 그 회사 관리자가 승인해야 'approved'로 바뀌고 그제서야
  // 회사 데이터(명함/프로젝트 등)에 접근할 수 있다. 최초 가입자(관리자)는 바로 'approved'.
  // 값이 없는(undefined) 기존 계정들은 이 기능이 생기기 전에 가입한 것이므로 승인된 것으로 간주한다.
  approvalStatus?: 'approved' | 'pending';
  // [추가] 이메일 인증 여부. 가입 시 false로 시작하고, 메일로 받은 링크를 클릭해야
  // true가 된다. 값이 없는(undefined) 기존 계정은 이 기능이 생기기 전에 가입한
  // 것이므로 인증된 것으로 간주한다(true 취급).
  emailVerified?: boolean;
  // [추가] 토스페이먼츠 구독 결제 상태. 회사(company) 관리자 계정에만 의미가 있다 —
  // 그 회사 전체의 구독 여부를 관리자 한 명의 결제 정보로 관리한다.
  // - plan: 'free'(무료, 기본 기능만) | 'pro'(구독 결제 완료, 전체 기능)
  // - subscriptionStatus: 결제 진행 상태. 'active'가 아니면 pro 기능이 잠긴다.
  plan?: 'free' | 'pro';
  subscriptionStatus?: 'none' | 'active' | 'past_due' | 'canceled';
  nextBillingAt?: string; // ISO 날짜문자열 — 다음 자동결제 예정일
  // [추가] 가입 일시. "가입 회원 & 협업 디렉토리"/운영현황에서 회사를 최근 가입순으로
  // 정렬하는 데 사용한다.
  createdAt?: string;
  // [추가] 전자결재에서 승인할 때 도장처럼 찍히는 손글씨 서명 이미지. 한 번 그려서
  // 등록해두면 이후 결재마다 재사용된다. base64로 들어오면 서버가 Supabase Storage에
  // 올리고 여기엔 그 주소(URL)만 저장한다 (다른 사진 필드들과 동일한 방식).
  signatureImage?: string;
}

export interface RegisteredUser extends User {
  password?: string;
  // [수정] 언제 가입했는지 확인할 수 있도록 가입 일시 기록. 이 필드가 생기기 전에 이미
  // 가입되어 있던 계정은 값이 없을 수 있다(운영 현황 화면에서 "정보 없음"으로 표시).
  createdAt?: string;
  // [추가] 이메일 인증 토큰/만료시각 (서버 내부용, 클라이언트로는 절대 내려주지 않음)
  emailVerificationToken?: string;
  emailVerificationTokenExpiresAt?: number;
  // [추가] 토스페이먼츠 연동용 서버 전용 필드 (클라이언트로는 절대 내려주지 않음)
  // - tossCustomerKey: 토스에 등록하는 구매자 식별키 (추측 불가능한 무작위 값이어야 함)
  // - tossBillingKey: 카드 등록 완료 후 발급되는 빌링키. 이걸로 매달 자동결제를 청구한다.
  //   토스 정책상 한 번 발급되면 다시 조회할 수 없으므로, 발급 즉시 안전하게 저장해야 한다.
  tossCustomerKey?: string;
  tossBillingKey?: string;
  // [추가] 애플 캘린더(아이폰/아이패드/맥) 구독 연동용 토큰. 캘린더 앱은 로그인 세션 없이
  // 그냥 URL 하나로 주기적으로 GET 요청만 보내기 때문에, x-user-id 헤더 같은 일반
  // 인증 방식을 못 쓴다. 대신 추측 불가능한 무작위 토큰을 URL에 담아서 그 사람(회사
  // 스코프)을 식별한다. 최초로 "Apple 캘린더 연동" 기능을 켤 때 한 번 생성되고, 이후
  // 계속 재사용된다.
  calendarFeedToken?: string;
}

// === 통합 차량 관리 (Vehicle Management) ===

export interface Vehicle {
  id: string;
  modelName: string;     // 차량명 (예: 벤츠 E300 4Matic)
  plateNumber: string;   // 차량 번호 (예: 12가 3456)
  owner: string;         // 담당자 / 운전자
  purchaseDate: string;  // 구입/대여 일자
  initialMileage: number; // 최초 주행거리 (km)
  currentMileage: number; // 현재 주행거리 (km)
  fuelType: 'gasoline' | 'diesel' | 'hybrid' | 'electric' | 'lpg'; // 유종
  status: 'active' | 'maintenance' | 'retired'; // 운행가능, 정비중, 운행중단
  createdAt: string;
  // --- 추가된 필드들 ---
  modelYear?: string;     // 년식 (예: 2024년식)
  color?: string;         // 색상
  rentalType?: 'own' | 'long_rent' | 'lease' | 'short_rent' | 'short_lease'; // 임차구분
  rentalFee?: number;     // 임차료 (월, 원)
  insuranceCompany?: string; // 보험사
  insuranceStartDate?: string; // 보험 가입일자
  insuranceEndDate?: string;   // 보험 만기일자
  insuranceAgent?: string;     // 보험 담당자
  insuranceContact?: string;   // 보험 연락처
  beaconId?: string;           // 비콘 ID
  registrationDocumentUrl?: string; // 자동차 등록증 이미지/파일 URL (base64)
}

export interface DrivingLog {
  id: string;
  vehicleId: string;
  driverName: string;    // 운전자명
  date: string;          // 운행 일자
  purpose: string;       // 운행 목적 (업무용, 출퇴근, 출장 등)
  startMileage: number;  // 출발 시 주행거리 (km)
  endMileage: number;    // 도착 시 주행거리 (km)
  distance: number;      // 주행거리 (km)
  startPlace?: string;   // 출발지
  endPlace?: string;     // 목적지
  department?: string;   // 부서
  projectName?: string;  // 프로젝트명
  startAddress?: string; // 출발지 주소
  endAddress?: string;   // 목적지 주소
  memo?: string;         // 메모
  createdAt: string;
  contactId?: string;    // 연관 거래처 담당자 ID
}

export interface VehicleExpense {
  id: string;
  vehicleId: string;
  date: string;          // 지출 일자
  category: 'fuel' | 'toll' | 'parking' | 'maintenance' | 'tax_insurance' | 'other' | 'agency_drive' | 'beverage' | 'meal' | 'supplies' | 'custom'; // 주유비, 통행료, 주차비, 정비비, 세금/보험, 기타, 대리운전비, 음료, 식대, 물품 구입, 직접 입력
  categoryCustom?: string; // 직접 입력 카테고리명
  amount: number;        // 지출 금액 (원)
  memo?: string;         // 메모
  payMethod?: 'company_card' | 'personal_card' | 'cash'; // 결제 수단
  merchantName?: string;  // 상호명
  fuelVolume?: number;    // 주유량 (L)
  projectName?: string;   // 프로젝트명
  createdAt: string;
  contactId?: string;    // 연관 거래처 담당자 ID
  receiptImage?: string; // 영수증 이미지 (base64)
  // [추가] 운행기록 작성 중 스캔한 영수증인 경우, 어느 운행기록에서 나온 지출인지 연결.
  // 이 값이 있으면 운행기록 수정 화면에서 "이미 등록된 영수증 목록"으로 다시 불러와 보여줄 수 있다.
  drivingLogId?: string;
}

export interface VehicleMaintenance {
  id: string;
  vehicleId: string;
  date: string;          // 정비 예정/완료 일자
  title: string;         // 정비 내용 (예: 엔진오일 교환)
  cost: number;          // 정비 비용 (원)
  mileage: number;       // 정비 시점 주행거리 (km)
  shopName?: string;     // 정비소명
  shopContact?: string;  // 정비소 연락처
  status: 'scheduled' | 'completed'; // 예정됨, 정비완료
  memo?: string;         // 메모
  // [수정] 워런티(보증) 수리처럼 실제로는 돈이 안 나가는 정비(비용 0원)도 있는데, 예전엔
  // 법인카드/개인카드/현금 중 하나를 억지로 골라야 해서 등록이 어색했다. "해당없음"을
  // 추가해서 무료 정비도 자연스럽게 기록할 수 있게 한다.
  payMethod?: 'company_card' | 'personal_card' | 'cash' | 'none'; // 결제 수단 (none: 해당없음/무료)
  receiptImage?: string; // 정비 영수증/청구서 이미지 (base64)
  createdAt: string;
}

export interface MaintenanceInterval {
  id: string;
  vehicleId: string;
  itemType: string;         // 점검 항목 (엔진오일 교환 등)
  intervalKm?: number;      // km 주기
  intervalDays?: number;    // 일 주기
  lastServiceMileage?: number; // 마지막 점검 주행 거리 (km)
  lastServiceDate?: string; // 마지막 점검일
  alertKmBefore?: number;   // km 전 알림
  alertDaysBefore?: number; // 일 전 알림
  createdAt: string;
}

export interface WorkLogExpense {
  id: string;
  category: 'breakfast' | 'lunch' | 'dinner' | 'drinks' | 'fuel' | 'parking' | 'proxy' | 'purchase' | 'custom';
  categoryCustom?: string; // 직접 입력시 카테고리명
  amount: number;        // 지출 금액 (원)
  payMethod: 'company_card' | 'personal_card' | 'cash_personal' | 'cash_company'; // 결제 수단
  memo?: string;         // 메모
  vehicleId?: string;    // 연동된 차량 ID (선택)
  linkedVehicleExpenseId?: string; // 연동된 차량비용 ID (상호 연동용)
  receiptImage?: string; // 영수증 이미지 (base64)
}

export interface DailyWorkLog {
  id: string;
  date: string;          // 일일 일자 (YYYY-MM-DD)
  title: string;         // 제목
  author?: string;       // 작성자
  department?: string;   // 부서
  tasksToday: string;    // 금일 실시 사항 (taskEntriesToday를 합쳐서 만든 텍스트, 인쇄/엑셀/AI정제용)
  taskEntriesToday?: WorkLogDayEntry[]; // 금일 실시 사항 항목 목록 (하루에 여러 건, 각각 시작~종료 시간 지정 가능)
  tasksTomorrow: string; // 명일 예정 사항
  issues?: string;       // 특이 사항/미결 사항
  contactIds?: string[];  // 연관 거래처/인맥 ID 목록 (명함 ID)
  projectIds?: string[];  // 연관 프로젝트 ID 목록
  expenses?: WorkLogExpense[]; // 비용 추가 항목 리스트
  invitedUserIds?: string[]; // [추가] 이 일정에 초대된 같은 회사 동료(사용자) ID 목록 - 저장 시 새로 추가된 사람에게 알림 메일 발송
  createdAt: string;
}

export interface WorkLogDayEntry {
  id: string;
  // [추가] 아이폰 캘린더의 "신규 이벤트"처럼, 항목마다 자기만의 시작/종료 날짜를 가질 수
  // 있게 함(여러 날에 걸친 일정 표현 가능). 비워두면 이 항목이 속한 일지의 날짜(일일 업무일지의
  // date, 또는 주간 업무일지에서 그 항목이 들어있는 요일에 해당하는 날짜)를 그대로 쓴다.
  startDate?: string;    // 시작 날짜 (YYYY-MM-DD)
  endDate?: string;      // 종료 날짜 (YYYY-MM-DD) - 비워두면 시작 날짜와 동일(당일)
  startTime?: string;   // 시작 시간 (예: "09:00")
  endTime?: string;     // 종료 시간 (예: "10:30")
  content: string;      // 해당 시간대 업무 내용
}

// === 전자결재 (Electronic Approval) ===

export type ApprovalStatus = 'draft' | 'pending' | 'approved' | 'rejected';

// 결재선 한 단계 (예: 기안자 / 경영지원실장 / 기술이사 / 대표이사)
export interface ApprovalStep {
  role: string;   // 직책/직위 라벨
  name?: string;   // 결재자 이름
  date?: string;   // 결재(승인) 일자 YYYY-MM-DD, 비어있으면 미결
  // [추가] 승인하는 순간의 결재자 서명 이미지를 그대로 남겨둔다(스냅샷). User.signatureImage를
  // 그때그때 참조하지 않고 복사해두는 이유: 나중에 그 사람이 서명을 다시 그려서 바꾸더라도,
  // 이미 승인된 예전 문서에는 "그 당시 실제로 찍힌 서명"이 그대로 남아있어야 하기 때문
  // (전자결재 문서의 무결성/증빙 목적).
  signatureUrl?: string;
}

export type LeaveCategory =
  | 'monthly'   // 월차
  | 'annual'    // 연차
  | 'official'  // 공가
  | 'sick'      // 병가
  | 'special'   // 특별휴가 (세부 종류는 specialType 필드로 구분: 출산/하기/경조/재해/직접입력)
  | 'health'    // 보건
  | 'other';    // 기타

export type LeaveSpecialType = 'birth' | 'summer' | 'family' | 'disaster' | 'custom';

// 연차 사용 단위: 년차(하루 종일, 1일) / 반차(4시간, 0.5일) / 반반차(2시간, 0.25일)
export type LeaveAnnualType = 'full' | 'half' | 'quarter';

// 휴가 신청서
export interface LeaveRequest {
  id: string;
  draftNumber: string;         // 기안번호 (예: 20260708-01)
  department: string;           // 소속
  author: string;                // 휴가자
  leaveCategory: LeaveCategory;  // 휴가 구분
  leaveCategoryCustom?: string;  // 기타 선택시 직접 입력
  specialType?: LeaveSpecialType;   // 특별휴가 선택시 세부 종류
  specialTypeCustom?: string;       // 특별휴가 세부 종류가 직접입력일 때의 텍스트
  annualType?: LeaveAnnualType;     // 연차 선택시 사용 단위 (년차/반차/반반차)
  totalAnnualDays?: number;         // 연차 선택시, 그 해 전체 부여된 연차 일수 (누적 표기 계산용)
  reason: string;                // 사유
  startDate: string;             // 시작일 YYYY-MM-DD
  endDate: string;               // 종료일 YYYY-MM-DD
  startTime?: string;            // 시작 시간 (반차 등)
  endTime?: string;              // 종료 시간
  days: number;                   // 산정된 휴가 일수
  annualLeaveNote?: string;      // 연차 사용/잔여 표기 (예: "5일/20일")
  homeContact?: string;          // 자택 연락처
  mobileContact?: string;        // 휴대폰
  actingPerson?: string;         // 직무 대행자
  submittedDate: string;         // 신청일 (문서 하단 날짜)
  approvalLine: ApprovalStep[];  // 결재선
  status: ApprovalStatus;
  approverMemo?: string;
  createdAt: string;
  // [추가] 두 결재자가 거의 동시에 이 문서를 승인/반려하면, 나중에 도착한 요청이 먼저
  // 처리된 결재 내용을 조용히 덮어써버리는 문제가 있었다. 서버가 저장할 때마다 이 값을
  // 새로 찍어두고, 승인/반려 요청 시 클라이언트가 자기가 마지막으로 읽은 시점의 이 값을
  // 같이 보내면, 그 사이 다른 사람이 먼저 처리해서 값이 달라졌을 때 서버가 감지해서
  // 거부할 수 있다(server.ts의 PUT /api/approvals/leave/:id 참고).
  updatedAt?: string;
}

export interface AdvancePaymentItem {
  id: string;
  date: string;          // 날짜
  project?: string;       // 프로젝트명
  description: string;    // 내용
  amount: number;          // 금액(원)
  account?: string;        // 계정과목
  companyName?: string;    // 상호
  remark?: string;         // 비고
  // [수정] 차량비용/정비/업무일지에서 "가져오기" 할 때 원본에 첨부된 영수증 사진도 같이 가져오기 위한 필드
  receiptImage?: string;
}

// 가지급금 정산서
export interface AdvancePaymentSettlement {
  id: string;
  companyName: string;     // 회사명
  periodStart: string;      // 기간 시작
  periodEnd: string;        // 기간 종료
  department: string;       // 부서
  author: string;            // 작성자
  draftDate: string;        // 기안일
  items: AdvancePaymentItem[]; // 정산 내역
  approvalLine: ApprovalStep[]; // 결재선
  status: ApprovalStatus;
  approverMemo?: string;
  createdAt: string;
  // [추가] 동시 승인/반려 충돌 감지용 (LeaveRequest.updatedAt 설명 참고)
  updatedAt?: string;
}

// [추가] 공문서 (대외 발송용 공식 문서 - 시험성적서 제출 건 등). 회사 레터헤드 형식의
// "수신자/참조/제목 + 번호 매겨진 본문 + 결재란 + 시행번호/접수 + 발신처 정보" 양식을 그대로 재현한다.
export interface OfficialDocument {
  id: string;
  companyName: string;        // 발신 회사명 (상단 레터헤드)
  author: string;              // 기안자(작성자) - 문서 하단 레터헤드에는 안 찍히지만, 결재 요청 알림 이메일 등
                                // 내부적으로 "누가 상신했는지" 표시할 때 쓰인다(수신자와는 다른 개념).
  recipient: string;           // 수신자
  reference?: string;          // 참조
  subject: string;              // 제목
  bodyParagraphs: string[];    // 본문 문단들 (출력 시 1. 2. 3. ...으로 자동 번호가 매겨지고, 마지막 문단 뒤에 "- 끝 -"이 붙는다)
  issueDate: string;            // 시행일자 YYYY-MM-DD (시행번호 옆 괄호 안에 표시되는 날짜)
  // [추가] 시행번호 (예: KS-20260816-001). 접두어-YYYYMMDD-일련번호 형식이며, 일련번호는
  // 같은 날짜(YYYYMMDD)로 이미 만들어진 공문서 개수 + 1로 계산되어 날짜가 바뀌면 001부터 다시 시작한다.
  executionNumber: string;
  receiptNumber?: string;       // 접수번호 (수신 측에서 접수 시 기재하는 칸, 보통 공란으로 둠)
  companyAddress?: string;      // 발신처 주소 (하단에 표시)
  companyPhone?: string;        // 발신처 전화
  companyFax?: string;          // 발신처 전송(팩스)
  companyEmail?: string;        // 발신처 이메일
  approvalLine: ApprovalStep[]; // 결재선 (예: 담당/이사/대표)
  status: ApprovalStatus;
  approverMemo?: string;
  createdAt: string;
  // [추가] 동시 승인/반려 충돌 감지용 (LeaveRequest.updatedAt 설명 참고)
  updatedAt?: string;
}

export interface WeeklyWorkLog {
  id: string;
  startDate: string;     // 주간 시작일 (YYYY-MM-DD)
  endDate: string;       // 주간 종료일 (YYYY-MM-DD)
  title: string;         // 제목
  author?: string;       // 작성자
  department?: string;   // 부서
  achievementsThisWeek: string; // 금주 실시 사항
  achievementsByDay?: {   // 요일별 실시 사항 (achievementEntriesByDay를 합쳐서 만든 텍스트, 인쇄/엑셀/AI정제용)
    mon?: string;
    tue?: string;
    wed?: string;
    thu?: string;
    fri?: string;
    sat?: string;
    sun?: string;
  };
  achievementEntriesByDay?: {   // 요일별 업무 항목 목록 (하루에 여러 건, 각각 시작~종료 시간 지정 가능)
    mon?: WorkLogDayEntry[];
    tue?: WorkLogDayEntry[];
    wed?: WorkLogDayEntry[];
    thu?: WorkLogDayEntry[];
    fri?: WorkLogDayEntry[];
    sat?: WorkLogDayEntry[];
    sun?: WorkLogDayEntry[];
  };
  plansNextWeek: string;        // 차주 예정 사항
  feedbacks?: string;           // 애로 및 건의 사항/피드백
  contactIds?: string[];  // 연관 거래처/인맥 ID 목록 (명함 ID)
  projectIds?: string[];  // 연관 프로젝트 ID 목록
  expenses?: WorkLogExpense[]; // 비용 추가 항목 리스트
  invitedUserIds?: string[]; // [추가] 이 주간 업무일지에 초대된 같은 회사 동료(사용자) ID 목록 - 저장 시 새로 추가된 사람에게 알림 메일 발송
  createdAt: string;
}

// === 전체 문의하기 (Feedback) ===
// [수정] 명함뿐 아니라 앱 전체 어디서나 접수 가능한 문의. 회사별로 나뉘지 않고
// 개발자(운영자)에게 전부 모이는 전역 데이터라서, 다른 데이터처럼 회사 스코프로 나누지 않는다.
export type FeedbackCategory = 'bug' | 'feature' | 'other';

export interface FeedbackItem {
  id: string;
  category: FeedbackCategory;
  content: string;
  authorName?: string;      // 작성자 이름 (로그인 정보 자동 기입)
  authorEmail?: string;      // 작성자 이메일
  authorPhone?: string;      // [수정] 답변/연락을 위해 작성자 핸드폰 번호도 같이 기록 (로그인 정보에 등록되어 있는 경우)
  companyName?: string;      // 작성자 소속 회사명 (개인 계정이면 비어있음)
  pageContext?: string;      // 문의를 남긴 시점의 화면(탭) - 어디서 접수됐는지 참고용
  status: 'new' | 'in_progress' | 'resolved';
  createdAt: string;
}

// === 명함 스캔 초대(바이럴 루프) ===
// [수정] 명함 상세보기에서 "이 분에게 앱 추천하기"를 보낸 기록. 실제 가입 전환까지는
// 추적하지 않고(가입 화면 쪽 파일이 필요해 범위 밖), "누가 몇 명에게 보냈는지" 발송 이력만 기록한다.
export interface InviteRecord {
  id: string;
  contactId?: string;      // 어떤 명함(사람)에게 보냈는지
  contactName?: string;
  channel: 'sms' | 'email' | 'kakao' | 'share' | 'other';
  sentByUserId?: string;
  sentByUserName?: string;
  sentAt: string;
}
